### ISSUE TITLE
Modify Existing Launch Configuration in an Auto Scaling Group

### ISSUE THREAD

**Issue by grayaii** [boto/boto#1537]
I have an existing Auto Scaling Group with a Launch Configuration. It has instances scaling up and down and all is good.

I now want to modify this Auto Scaling Group by tweaking its Launch Configuration.

How do I do this with boto?
(quoted from: https://forums.aws.amazon.com/thread.jspa?threadID=44120)
By using the "as-update-auto-scaling-group" tool, you create a new launch configuration, and then you use as-update-auto-scaling-group to set the group to use the newly-created launch config. 

Any ideas how I can do this in boto?
Thanks!

**Comment by einarc** [comment]
@grayaii  I'm thinking of essentially doing this:

1.-use Get LC to get the parameters of the current LC.
2.-Use the parameters to create a copy and name it copy
3.-Assign copy to ASG
4.-Delete original LC
5.-Create new LC with whatever parameters I want and the same name as the original.


Now here's another option:

1.-use Get LC to get the parameters of the current LC.
2.-Compare the parameters with the new parameters. If new parameter exist overwrite original parameter.
3.-Create new version with updated parameters
4.-Assign new version to ASG

What did you do?

Thank You!

**Comment by revmischa** [comment]
@einarc you may wish to look at https://github.com/revmischa/udo/blob/master/udo/launchconfig.py#L138
