### ISSUE TITLE
generate_url raises exception for anonymous connections

### ISSUE THREAD

**Issue by srobertson** [boto/boto#1540]
It would be nice to be able to call generate_url on keys from anonymous connections

Right now if you open a connection anonymously

  conn = boto.connect_s3(anon=True)

Then later try to call generate_url on a key form the bucket, it fails with the following exception.

AttributeError: 'AnonAuthHandler' object has no attribute '_hmac_256'

**Comment by zachmullen** [comment]
Bump, just ran into the same thing. I have to workaround this by manually generating the download URL.

**Comment by edmorley** [comment]
**STR:**
```
import boto
s3 = boto.connect_s3(anon=True)
print(s3.generate_url(0, 'GET', bucket='examplebucket', key='test.txt', query_auth=False))
```

**Expected:**
```
https://examplebucket.s3.amazonaws.com/test.txt
```

**Actual:**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "boto/s3/connection.py", line 411, in generate_url
    b64_hmac = self._auth_handler.sign_string(c_string)
  File "boto/auth.py", line 132, in sign_string
    new_hmac = self._get_hmac()
  File "boto/auth.py", line 124, in _get_hmac
    if self._hmac_256:
AttributeError: 'AnonAuthHandler' object has no attribute '_hmac_256'
```

The `self._auth_handler.sign_string()` call here should be inside the `query_auth` conditional:
https://github.com/boto/boto/blob/af045f93d70fbb4cdac2a8e57d040ce59935d45b/boto/s3/connection.py#L411-L416

In addition, the conditional should probably also take into account `self.anon` (ie: if `anon=True` don't require `query_auth` to have been explicitly set to `False`).

I'll open a PR.
