### ISSUE TITLE
add retry mechanism in some scenarios with 4XX HTTP response 

### ISSUE THREAD

**Issue by henrysher** [boto/boto#1618]
I'd suggest boto could support retry in some scenarios with 4XX HTTP response.

The first one is that 400 bad request in Route53 API.
Route53 document describes: http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html

" If Route 53 can't process a request before the next request arrives, it will reject subsequent requests for the same hosted zone and return an HTTP 400 error (Bad request)..."

As we know, 400 bad request is for client errors. However, in this case, it actually means that Route53 servers cannot handle this new request due to the last one still in processing -- mostly it could be considered as Server errors. Therefore, it is really necessary for boto to add retry mechanism on this scenario. Boto's retry mechanism will have increasing sleeping time in later retries. So retry will not make things worse.

Here is how i could get this error:
My application has many roles. Each role has many instances. Each instance has its own R53 DNS record. In instance bootstrapping, it will add its own record itself and delete it when shutting down. And all of these records are in the same hosted zone. So when auto-scaling group takes actions (like health check replacing or scaling due to the policy) , it is really possible that many record change requests happen in this hosted zone. Thus the 400 bad request will happen frequently.

Currently, boto only retries in 500 and 503 for HTTP responses. I suggest to adding this 400 bad request with retry mechanism.

If later I find any new scenarios, I will add them here.

Thanks
Henry

**Comment by arforde** [comment]
Retry mechanism is broken again. It seems the responses have changed and "code" is no longer a header but is contained in the response. Hit this during throttling no retry was attempted.

**Comment by tdm4** [comment]
I've hit this during throttling today (AWS is having an issue with this at the moment).
There is no way to retry.
