### ISSUE TITLE
Basic GCM SNS Mobile Push Not Working

### ISSUE THREAD

**Issue by eswenson1** [boto/boto#1692]
I cannot seem to get a very basic use case of SNS Mobile Push using boto (2.10) to work.  When I use the exact same message payload on AWS's webapp for using SNS Mobile Push (https://console.aws.amazon.com/sns/home), I see the expected message ("foo") appear on my Android device.  However, when I use boto, "null" appears on my Android device.  I've tried lots of different flavors of messages (where the value of "GCM" is not a string, but more nested JSON structure), to no avail.  The documentation has no examples of GCM SNS Mobile Push, so I'm flying blind.  

A simple app that demonstrates the issue appears here:  http://pastebin.com/xk0Ep50Q.  The target_arn has its last few characters obscured so as not to invite hackers to send stuff to my device, but when the correct value is used, I _do_ receive push messages -- just the wrong value.

**Comment by danjger** [comment]
Regarding sending push message to android using SNS Publish 
I can't get the AWS CLI (based on boto) or Paws (also based on boto) to send the message payload no matter how I format it.
I get the notification but it is empty.
Using the AWS console I get the message.
if I execute this aws cli for a working target-arn
```
aws sns publish --target-arn <endpoint arn> --message 'hi aws cli'
```
it works for iOS and only the icon shows for android.
I've tried using Paws with perl and I get the same result.
I have a java implementation that seems to work but I'd have to confirm it is with the same parameters.
Has anyone gotten an SNS message through to an android client using boto?

**Comment by biranchi2018** [comment]
Its 2018 and its still not working... Amazon really needs to fix it in SNS.
