### ISSUE TITLE
dynamoDB local usage

### ISSUE THREAD

**Issue by mtakemiya** [boto/boto#1818]
I was unable to find documentation saying how to connect to a local instance of the dynamodb server (localhost). After spending a few days on this, I am still unable to use boto to connect to my local server, so please consider adding documentation, specifically how to configure boto to look for dynamodb on localhost and use the provided access key.

**Comment by bhadram59** [comment]
@danielgtaylor  I have implemented the same class available inside the document of dynamodbv2 to connect the DynamoDbLocal. For me it is returning the empty list of tables. But I have around 7 to 8 tables in my DB. So please give me some suggestions.
I am getting below response only.
{u'TableNames': []}"

**Comment by bhadram59** [comment]
@danielgtaylor  Instead of creating the db name "accessid_regionname", the boto creating the db name like "accessid_host". Why it is doing like that?
