### ISSUE TITLE
Add support for CopyDBSnapshot

### ISSUE THREAD

**Issue by tomstockton** [boto/boto#1865]
Announced here: http://aws.typepad.com/aws/2013/10/cross-region-snapshot-copy-for-amazon-rds.html

API Reference: http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CopyDBSnapshot.html

Please and thank you!

Tom

**Comment by SkyRocknRoll** [comment]
Hello the above is working fine for all the regions except newly added eu-central-1. When i try to copy rds snapshot from us-east-1 to eu-central-1 DBSnapshotNotFound Exception is occuring. The same snapshot if i copy to us-west-1 it works.
