### ISSUE TITLE
InvalidAccessKeyId when using same access key and secret as default settings

### ISSUE THREAD

**Issue by youngneh** [boto/boto#1971]
version: 2.22.0

When I explicitly create the connection with the same access and secret key as a connection created by using an instance's metadata, it says the access key id could not be found.

This code was run on my ec2 instance. This instance was created by an autoscale group with a configured iam role that has permissions to the s3 bucket. 

``` python
>>> import boto
>>> c1 = boto.connect_s3()
>>> c2 = boto.connect_s3(c1.aws_access_key_id, c1.aws_secret_access_key)
>>> b1 = c1.get_bucket('bucketname')
(does not error out)
>>> b2 = c2.get_bucket('bucketname')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/boto/s3/connection.py", line 391, in get_bucket
    bucket.get_all_keys(headers, maxkeys=0)
  File "/usr/lib/python2.6/site-packages/boto/s3/bucket.py", line 360, in get_all_keys
    '', headers, **params)
  File "/usr/lib/python2.6/site-packages/boto/s3/bucket.py", line 327, in _get_all
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><RequestId>0967DD9AD651209F</RequestId><HostId>...</HostId><AWSAccessKeyId>...</AWSAccessKeyId></Error>
```

On top of this I discovered some sporadic failing of the default boto.connect_s3() call as well (with the same InvalidAccessKeyId error). But I can't reproduce this at the moment. 

Thank you,
-Alex

**Comment by felipe-vvoosh** [comment]
The token expiration is after more than 8 hours, I'm getting the error in less than 10 min...
