### ISSUE TITLE
Redshift parameters - work load management (WLM)

### ISSUE THREAD

**Issue by neilmcbride1** [boto/boto#2006]
Within a Redshift Parameter Group one can define the "WLM" settings. These are critical to the running of processes in Redshift. It would be great if the setting of these could be added to Boto

**Comment by vmdx** [comment]
Today I had the same issue, here is what I eventually got to work:

    wlm_json_configuration = [
    {'query_concurrency': 5, 'memory_percent_to_use': 50, 'query_group': 'hello', 'user_group': 'goodbye'},
    {'query_concurrency': 10, 'memory_percent_to_use': 50, 'max_execution_time' : 300000}
    ]
    c.modify_cluster_parameter_group('my-pgroup', [('wlm_json_configuration', json.dumps(wlm_json_configuration))])
