### ISSUE TITLE
get_bucket has an expensive default

### ISSUE THREAD

**Issue by jasonroelofs** [boto/boto#2078]
http://www.appneta.com/blog/s3-list-get-bucket-default/

When `get_bucket` is called, by default it also does a full LIST because `validate` defaults to `True`. Thus, anyone using this library is accidentally paying way more for S3 than they should. This default should be `False`.

**Comment by neilsh** [comment]
Do we need to upgrade the boto used by redshift_ingress? In the requirements.txt it looks like it still uses boto 2.9.4, and the fix is introduced in versions 2.25 and later. dashboard_ui and alerts also have requirements.txt lines "boto>=2.20.1"

**Comment by Deepakdubey90** [comment]
Hi All, 
I'm getting error while using default value of get_bucket method:
**Error >>>** 
>>> bucket = conn.get_bucket("schemafiles")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/boto/s3/connection.py", line 503, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/boto/s3/connection.py", line 550, in head_bucket
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request
**>>>>**

When I have tried to access the bucket default validate=False, its returning the bucket. but in that case getting error during S3 file upload .
ERROR ::

*** S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>676528A563EF0FFB</RequestId><HostId>h/iUjaTEdIS84tFPY7eQYh2tGv6AR5JmhC3V6ZbCJGu1ulM/YDOx2ANrjxD53Z+U6TC1MkDutSo=</HostId></Error>
>>>>>>>>>>>>>>>>>>>>>>

Any Help Appreciate.
Thanks
