### ISSUE TITLE
Support for region in SWF Layer 2 (without using config)

### ISSUE THREAD

**Issue by sukrit007** [boto/boto#2136]
The Layer2 API does not support passing of region to layer 1. The only way we can set the region is , if it were part of the boto config.

https://github.com/boto/boto/blob/develop/boto/swf/layer2.py#L36

We should allow passing of region from layer2 to layer1.

**Comment by wmaiouiru** [comment]
Can we update the documentation for this as well? http://boto.readthedocs.org/en/latest/ref/swf.html#module-boto.swf.layer2 
I had to look for source-code to use the feature: 
import boto.swf
import boto.swf.layer2 as swf 
aws_region=None
for reg in boto.swf.regions():
	if reg.name == 'us-west-2':
		aws_region = reg
		break
swf.Domain(name=DOMAIN,region=aws_region)

**Comment by markdoliner** [comment]
+1, would be great if this was documented. Would also be nice to be able to pass the region name to boto.swf.layer2.Domain() and have it look up the Region object.
