### ISSUE TITLE
spot instance request for instances in a vpc have wrong security group.

### ISSUE THREAD

**Issue by rohitagarwal003** [boto/boto#2293]
I was trying to start a spot instance in my vpc and got hit with a weird bug - the security group which got associated with the spot request didn't match the security group associated with the instance.
I provided the vpc security group in a network interface specification and sent that network interface along with the spot request. Everything worked fine: the request succeeded, the instance got started with the desired security group etc. The only problem was that the spot request was showing the wrong security group - instead of the provided security group it showed the default security group for the account.

``` pycon
>>> import boto
>>> boto.Version
'2.28.0'
>>> import boto.ec2
>>> conn = boto.ec2.connect_to_region("us-east-1")
>>> nis = boto.ec2.networkinterface.NetworkInterfaceSpecification(
...         subnet_id="subnet-a1b2c3d4",
...         associate_public_ip_address=True,
...         groups=[A_VPC_GROUP])
>>> nic = boto.ec2.networkinterface.NetworkInterfaceCollection(nis)
>>> conn.request_spot_instances(0.1, "ami-abcd1234",
...         network_interfaces=nic)
[SpotInstanceRequest:sir-12345678]
>>> conn.get_all_spot_instance_requests(
...         filters={"launch.group-id": A_VPC_GROUP})
[]
>>> conn.get_all_spot_instance_requests(
...         filters={"launch.group-id": NON_VPC_DEFAULT_GROUP})
[SpotInstanceRequest:sir-12345678]
```

This is quite possibly a bug in the EC2 API. But using the UI, I was unable to reproduce it as you cannot specify a network interface while requesting a spot instance from the UI.

**Comment by bsnote** [comment]
It looks like this bug hasn't been fixed yet. Where can it be tracked?

**Comment by mindprince** [comment]
I would suggest opening a support case with AWS.

I checked my mails, they didn't provide a timeline for when the API behavior would be fixed. They suggested a workaround. Using the following filter works correctly:
```
conn.get_all_spot_instance_requests(filters={"network-interface.group-id" : A_VPC_GROUP})
```

**Comment by bsnote** [comment]
Thank you, Rohit!
