### ISSUE TITLE
bin/glacier does not work on Python 3.x

### ISSUE THREAD

**Issue by winny-** [boto/boto#2490]
Hi! So the README says glacier is Python 3 compatible, however the `bin/glacier` command does not appear to be Python 3 compatible.

## Error on Python 3.x
Tested on Python 3.4.

```
$ glacier --version
  File "/home/glacier/local/bin/glacier", line 81
    """
      ^
SyntaxError: invalid syntax
```

## Steps to reproduce
1. Install Python 3
2. `pip3 install boto`
3. `glacier --help` causes the above error.

## Version tested

```
$ python3
Python 3.4.1 (default, Aug  1 2014, 22:33:49)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto
>>> boto.__version__
'2.32.0'
```

**Comment by kyleknap** [comment]
Looks like Daniel fixed this. Closing.
