### ISSUE TITLE
glacier: 400 Response During Multipart Upload

### ISSUE THREAD

**Issue by averigin** [boto/boto#2524]
Python: 3.4.1
Boto: 2.32.1
Related Issue: #2493 

When uploading a file larger than 100MB to glacier via Boto (using `vault.upload_archive()`), I recieved the following exception:
`boto.glacier.exceptions.UnexpectedHTTPResponseError:
	Expected (204,), got (400, b'{"code":"InvalidParameterValueException","message":"Invalid Content-Range: bytes%200-4194303/*","type":"Client"}')`
This is only an issue with multi-part uploads. I do not get any errors when uploading files less than 100MB since these do not generate multipart requests.

It appears that the space in the `Content-Range` header is being unnecessarily URL-encoded to `%20`. According the the HTTP spec, spaces are a valid characters within the text field of any header field (http://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html#sec2.2). If I add space to the list of safe characters (`HTTPRequest.authorize()` in `boto\connection.py`), the exception is no longer thrown.

**Comment by gaqzi** [comment]
@az0's patch worked like a charm for me too, how come it hasn't been merged in? 
@danielgtaylor *poke* :wink:

**Comment by AkshivBaluja** [comment]
Thanks for this Patch ! I used Python 3.4 and Boto 2.36

**Comment by BackendButters** [comment]
Patch works for me fine, too with Python 3.4 & boto 2.36.

**Comment by robert-wallis** [comment]
Also confirming @az0's patch works perfectly.  Do any Boto Admins still work on this project?  This and issue #2603 mean Glacier and Boto do not work from pip installs.

**Comment by acharrett** [comment]
I'd like to say that this patch is really needed too.  It fixed my issue uploading files larger than 100MB to Glacier on both python 3.4 and 3.5
