### ISSUE TITLE
boto.glacier.vault.Vault.list_jobs doesn't check for Marker

### ISSUE THREAD

**Issue by cperl82** [boto/boto#2565]
According to [1], the "List Jobs" request will contain at most 1000 jobs in the response.  If there are more jobs, the response will contain a marker that should be included in the next request to continue the paginated response.

It looks like `Vault.list_jobs` doesn't do the necessary checking of `Marker` in the return.  It should behave similarly to `Vault.list_all_parts`.

[1] http://docs.aws.amazon.com/amazonglacier/latest/dev/api-jobs-get.html

**Comment by Bustead** [comment]
@cperl82 do you know if this issue was resolved in boto3?

**Comment by cperl82** [comment]
Sorry, no idea.

**Comment by Bustead** [comment]
I'm happy to investigate further, but if this isn't really an issue for you how do you feel about closing it, even if it's not resolved?

**Comment by cperl82** [comment]
This issue is 9 years old! I have no interest in it anymore, so I'll close it.
