### ISSUE TITLE
ModifySubnetAttribute is missing

### ISSUE THREAD

**Issue by vamitrou** [boto/boto#2646]
Hi, I miss the "ModifySubnetAttribute" API call and implemented it under boto/ec2.
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-ModifySubnetAttribute.html

The problem is that the call seems to be dropped by the service:

```<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidAction</Code><Message>The action ModifySubnetAttribute is not valid for this web service.</Message></Error></Errors><RequestID>c95f7d0d-5359-4397-8713-66619eee0073</RequestID></Response>```

Can someone offer some assistance on that?

You can find my patch here:
https://github.com/vamitrou/boto/commit/6b5375a238e9759223f8a21251215024ffc5a7a2

I also tried sending POST request but got the same error.

Thanks,
Vasileios

**Comment by rayrayson** [comment]
Finally wrote the unit test, and created a pull request -- see PR #3111.

**Comment by scoates** [comment]
:+1:

**Comment by FlorinAndrei** [comment]
Wow, this is extremely useful, please merge!

**Comment by JordonPhillips** [comment]
We are no longer providing service updates to boto 2.x, for additional features please use boto3, which can be used in conjunction with boto 2.x if necessary. [Here](http://boto3.readthedocs.org/en/latest/reference/services/ec2.html#EC2.Client.modify_subnet_attribute)'s that operation in the boto3 docs. As far as the PR is concerned, it will need tests before we can consider merging it in.
