### ISSUE TITLE
Get Python SDK release notes hosted on the AWS Amazon site as per ruby

### ISSUE THREAD

**Issue by geekpete** [boto/boto#2648]
http://aws.amazon.com/releasenotes/Ruby/0775179500326517

Not having Python release notes on the Amazon site as per the Ruby release notes makes the Python SDK seem more like an unofficial library compared to the Ruby SDK.

We need to get Boto resources hosted on the Amazon site as per Ruby.

**Comment by Bustead** [comment]
@geekpete do you mean like this page?

https://aws.amazon.com/sdk-for-python/

**Comment by geekpete** [comment]
This is a really old issue, wow 9 years.
Seems there are similar release notes for python as the Ruby one I compared.

https://aws.amazon.com/about-aws/whats-new/2014/08/11/aws-sdk-for-python-boto-now-supports-python-3/

Add to that the url for the main Python SDK page and this issue seems solved or no longer relevant by now.

**Comment by geekpete** [comment]
Not to mention this entire package is itself deprecated now by boto3.

**Comment by Bustead** [comment]
I'm not entirely sure why CodeTriage keeps pointing me to the Boto package instead of Boto3, but I'm going along for the ride :p
