### ISSUE TITLE
DynamoDB Document Data Types

### ISSUE THREAD

**Issue by Katafalkas** [boto/boto#2737]
I cant seem to find if `boto` supports it, and if it does - it does not seem to be documented or I just cant find it.

If i try to add
```
doc = {
‘first’: 1,
‘second’: 2,
‘items’: [{‘item_id’: 1, ‘foo’: 1, ‘bar’: 0},
          {'item_id': 2, ‘foo’: 100, ‘bar’: 20}
          ]
}
```

with: `foobar.put_item(doc)`

I get: `TypeError: Unsupported type "<type 'list'>" for value "[{‘item_id’: 1, ‘foo’: 1, ‘bar’: 0},{'item_id': 2, ‘foo’: 100, ‘bar’: 20}]"`

and with: `con.put_item('foobar', doc)`

I get: 
```
boto.exception.JSONResponseError: JSONResponseError: 400 Bad Request
{u'Message': u'Expected null', u'__type': u'com.amazon.coral.service#SerializationException'}
```
I have seen some tickets and stackoverflow questions, but they all seem to lead to assumption that boto does not support it yet,

**Comment by jrydberg** [comment]
@xethorn why wouldn't it make it? not support all the data types that dynamodb supports feels kinda limiting.

**Comment by xethorn** [comment]
@jrydberg : Unsure. I think the owner of the repo has some concerns about retrocompatibility. Feel free to chime in the pull request.

**Comment by RonRothman** [comment]
Looks like this is fixed in boto v2.35.2.

**Comment by xethorn** [comment]
Yes – this issue should be marked as fixed.

**Comment by xethorn** [comment]
@Katafalkas @danielgtaylor, feel free to close. Thanks for merging the PR!

**Comment by arpansolanki** [comment]
Do we have any document or example for put item of Map type into dyanmodb using boto?

**Comment by xethorn** [comment]
Highly recommend to switch to Boto3: https://boto3.readthedocs.io/en/latest/guide/dynamodb.html#creating-a-new-item. 

If you cannot: 
http://docs.pythonboto.org/en/latest/ref/dynamodb2.html#boto.dynamodb2.table.Table.put_item

**Comment by ghostakstevelodx** [comment]
Do we have any example for put item of Map type  from excel file into dyanmodb using boto3?
