### ISSUE TITLE
SES region eu-central-1 wrongly enabled in boto

### ISSUE THREAD

**Issue by tmichelet** [boto/boto#2816]
Setup:
boto 2.34.0
Python 2.7.3

The `ses` namespace is enabled for the `eu-central-1` region ([see endpoints.json](https://github.com/boto/boto/blob/develop/boto/endpoints.json#L308)), whereas this region isn't available  according to the [aws documentation](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html)
![screen shot 2014-12-16 at 7 21 14 pm](https://cloud.githubusercontent.com/assets/1532259/5464611/b75bd8aa-8558-11e4-8725-5d795d6be7fd.png)

As a result, querying for ses data for `eu-central-1` fails:
```python
>>> import boto.ses
>>> boto.ses.regions()
[RegionInfo:us-west-2, RegionInfo:us-east-1, RegionInfo:eu-central-1, RegionInfo:eu-west-1]
>>> conn = boto.ses.connect_to_region(
        'eu-central-1',
        aws_access_key_id='<YOUR_AWS_KEY_ID>',
        aws_secret_access_key='<YOUR_AWS_SECRET_KEY>')
conn
SESConnection:email.eu-central-1.amazonaws.com
>>> conn.list_verified_email_addresses()
socket.gaierror: [Errno -2] Name or service not known
```

Removing the line from the ses regions solves this issue.

**Comment by jfunction** [comment]
Just found this through a google search - @tmichelet did you mean to link to [this line in endpoints.json](https://github.com/boto/boto/blob/develop/boto/endpoints.json#L341) ? 

That said I have not tried to replicate the error, I was just trying to figure out what regions were valid.

**Comment by jamesls** [comment]
This should be fixed now via https://github.com/boto/boto/pull/3491
