### ISSUE TITLE
Create a Table() instance doesn't call describe_table method under the hood as mentioned on docs

### ISSUE THREAD

**Issue by PauloMigAlmeida** [boto/boto#2826]
- A description of the problem/suggestion.
  
  I was just playing around with boto when I suddenly realised that as you create a Table instance (I'm using dynamodb2 module) it sets self.throughput to be 5 on both read and write keys but on docs it says it'd call describe_table under the hood to determine schema/indexes/throughput.
- How to recreate the bug.

``` Python
from boto.dynamodb2.table import Table

invitationTable = Table("INVITATION")
print 'Freshly created instance', invitationTable.throughput

invitationTable.describe()
print 'After call describe method', invitationTable.throughput
```

```
That outputs the following:
```

```
Freshly created instance {'read': 5, 'write': 5}
After call describe method {'read': 3, 'write': 3}
```

**Comment by arturhoo** [comment]
This is a pretty serious bug for systems that update a table's throughput dynamically and rely on previous information to restore to normal values.
