### ISSUE TITLE
def check_lowercase_bucketname(n) buggy

### ISSUE THREAD

**Issue by netvisao** [boto/boto#2833]
It fails for an acceptable s3 bucket name : "4652-5751-2377-XyzAbc"

How to reproduce:
1. Create a bucket with the suggested name above
2. 
```
    buckets = connection.get_all_buckets()
        for bucket in buckets:
            p = bucket.get_policy()
```
Part of the STrace:
```
line 59, in check_lowercase_bucketname
    raise BotoClientError("Bucket names cannot contain upper-case " \
boto.exception.BotoClientError: BotoClientError: Bucket names cannot contain upper-case characters when using either the sub-domain or virtual hosting calling format.

**Comment by galdwulf** [comment]
This error is "by design" by Amazon. S3 bucket names cannot contain uppercase letters - and cannot be created with uppercase letters - see http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by Bsami** [comment]
Is there a workaround for this ? The AWS console allows creating buckets with names containing upper-case characters and is able to describe them, shouldn't we be able to do the same with boto ?

**Comment by netvisao** [comment]
NOOP
