### ISSUE TITLE
Opsworks Register Instances

### ISSUE THREAD

**Issue by dieend** [boto/boto#2853]
AWS CLI now have register instances from EC2 to opsworks stack.

http://docs.aws.amazon.com/opsworks/latest/userguide/registered-instances-register.html
Register and Deregister instance:
http://docs.aws.amazon.com/cli/latest/reference/opsworks/register.html
http://docs.aws.amazon.com/cli/latest/reference/opsworks/deregister-instance.html
Assign and unassign registered instance to layer:
http://docs.aws.amazon.com/cli/latest/reference/opsworks/assign-instance.html
http://docs.aws.amazon.com/cli/latest/reference/opsworks/unassign-instance.html

It would be great to have it in boto, because by using only CLI, it is hard to assign the created instance to a layer automatically.

**Comment by kyleknap** [comment]
The PR adding support has now been merged. Closing.
