### ISSUE TITLE
Unexpected complex element termination - for using register_destination()

### ISSUE THREAD

**Issue by shandy-bixly** [boto/boto#2895]
I am getting the following error:
MalformedInput: MalformedInput: Bad Request 
Unexpected complex element termination

All I can find is that register_destination() requires both Destination and MarketplaceId, but when I provide those I get an error. I have tried providing the ARN and the URL for my Amazon SQS Queue as the Destination but neither is working. Is there something else I am missing?

conn.register_destination(
Destination='[url of queue]',
MarketplaceId=[marketplaceid]')

**Comment by shandy-bixly** [comment]
I did some more looking around and found the correct format is this:
conn.register_destination(
    MarketplaceId=settings.MWS_MARKETPLACE_ID,
    Destination={'DeliveryChannel': 'SQS',
                          'AttributeList': 
                             {'member':
                                       {'1' :
                                            {'Key': 'sqsQueueUrl',
                                             'Value': QUEUE_URL
                                             }
                                       }  
                             }
                          }
)

**Comment by disruptek** [comment]
Would you mind letting me know if the following works?  If it doesn't, we probably need to tweak the decorators `register_destination()` and its ilk.  Boto should be performing the transformation of lists on your behalf...

```python
conn.register_destination(MarketplaceId=settings.MWS_MARKETPLACE_ID,
    Destination={'DeliveryChannel': 'SQS',
        'AttributeList': [dict(Key='sqsQueueUrl', Value=QUEUE_URL)]
    })
```

**Comment by shandy-bixly** [comment]
Thanks. It is working. I was able to register my SQS Queue.
