### ISSUE TITLE
Unable to create instance in VPC subnet security group

### ISSUE THREAD

**Issue by pmondal08** [boto/boto#2912]
Hello Guys,

I am having trouble initializing a new EC2 instance in VPC subnet with security groups. 

2015-01-23 14:49:12,522 Response headers: [('transfer-encoding', 'chunked'), ('date', 'Fri, 23 Jan 2015 03:49:12 GMT'), ('cneonction', 'close'), ('server', 'AmazonEC2')]
2015-01-23 14:49:12,522 <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter groupName cannot be used with the parameter subnet</Message></Error></Errors><RequestID>f5e06003-f4f0-49a2-a120-32f5897d4d19</RequestID></Response>
2015-01-23 14:49:12,522 400 Bad Request
2015-01-23 14:49:12,522 <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter groupName cannot be used with the parameter subnet</Message></Error></Errors><RequestID>f5e06003-f4f0-49a2-a120-32f5897d4d19</RequestID></Response>

Thanks & Regards,
Parth

**Comment by amalgjose** [comment]
Hi,
Seems like you gave the subnet-id in the place of security group name. 

Regards,
Amal G Jose

**Comment by pmondal08** [comment]
Hi,

not working even if i use security groups that gives 

EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security groups 'sg-ebbdae87', 'sg-ea190b86', 'sg-1bb8ab77' do not exist</Message></Error></Errors><RequestID>45a1fa2c-bef2-47f0-8c91-e18d54beb081</RequestID></Response>

Here is my code which triggers the instance..

try:
                   conn.run_instances(
                             myami,
                             key_name='Target_Aus_Online',
                             instance_type=instance,
#                             subnet_id='subnet-9eef2bf7',
                             security_groups=['sg-ebbdae87', 'sg-ea190b86', 'sg-1bb8ab77'])
                   instance_list(new_env)
               except Exception, e:
                      msg = str(e)
                      print(msg)

**Comment by pmondal08** [comment]
Now its working....i had to add subnet id. 
try:
                   conn.run_instances(
                             myami,
                             key_name='Online',
                             instance_type=insta,
                             security_group_ids=['sg-ebbdae87', 'sg-ea190b86', 'sg-1bb8ab77'],
                             subnet_id='subnet-9eef2bf7')
                   instance_list(new_env)
