### ISSUE TITLE
setup.py typo

### ISSUE THREAD

**Issue by rboccabe** [boto/boto#2915]
When trying to follow the instructions for installation from source at https://github.com/boto/boto/blob/develop/README.rst:

$ git clone git://github.com/boto/boto.git
$ cd boto
$ python setup.py install 

I ran into the issue of:

error: package directory 'boto/awslamba' does not exist

I believe that in the setup.py file there is a typo in line 83, because the directory
boto/awslamba
does exist.

**Comment by tombenninger** [comment]
I noticed the same thing, and put in https://github.com/boto/boto/pull/2914. It is supposed to be 'awslambda' with a 'd'.

**Comment by jb-1980** [comment]
Same for me. Changing the typo caused the script to run without an error.

**Comment by kyleknap** [comment]
This should be fixed now. I merged the pull request https://github.com/boto/boto/pull/2914. It works for me now. Please reopen if issue persists.
