### ISSUE TITLE
Managed Policies Support

### ISSUE THREAD

**Issue by monkeysecurity** [boto/boto#2956]
AWS Just announced Managed Policies.

https://aws.amazon.com/blogs/aws/new-managed-policies-for-aws-identity-access-management/

Boto should support reading/updating managed policies and their versions.

**Comment by pnathan** [comment]
:+1: Love to see this implemented - is it much work to do?

**Comment by monkeysecurity** [comment]
# Relevant API calls:

SRC: http://docs.aws.amazon.com/IAM/latest/UserGuide/policies-managed-controlling-access.html

## Managed Policies
Create:
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_CreatePolicy.html
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_CreatePolicyVersion.html

Delete:
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_DeletePolicy.html
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_DeletePolicyVersion.html

Get:
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_GetPolicy.html
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_GetPolicyVersion.html

List:
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_ListPolicies.html
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_ListPolicyVersions.html

Other:
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_SetDefaultPolicyVersion.html

## Entities
List:
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_ListEntitiesForPolicy.html

Attach:
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_AttachGroupPolicy.html
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_AttachRolePolicy.html
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_AttachUserPolicy.html

Detach:
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_DetachGroupPolicy.html
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_DetachRolePolicy.html
- http://docs.aws.amazon.com/IAM/latest/APIReference/API_DetachUserPolicy.html

**Comment by defionscode** [comment]
Agreed, support for this is needed. If a managed policy is added to a resource, deletion via boto of that resource becomes impossible.

**Comment by harrisnb** [comment]
+1 Support for managed policies would be really great!

**Comment by eikonomega** [comment]
+1

**Comment by SkyRocknRoll** [comment]
+1

**Comment by eleniS** [comment]
+1

**Comment by memory** [comment]
+1

**Comment by tmichelet** [comment]
+1

**Comment by shaunbrady** [comment]
I am working on a PR for this.  I hope to have it submitted with in the week.

**Comment by viper233** [comment]
+1

**Comment by moizrizvi** [comment]
+1

**Comment by moizrizvi** [comment]
+1

**Comment by zeckalpha** [comment]
Since #3185 was merged, can this be closed?
