### ISSUE TITLE
Image.run doesn't match EC2Connection.run_instances

### ISSUE THREAD

**Issue by nchammas** [boto/boto#3054]
What is the difference between these two methods in terms of intended use case? It's not clear from the docs (boto v2.36.0).
- [`ec2.image.Image.run`](http://boto.readthedocs.org/en/latest/ref/ec2.html#boto.ec2.image.Image.run)
- [`ec2.connection.EC2Connection.run_instances`](http://boto.readthedocs.org/en/latest/ref/ec2.html#boto.ec2.connection.EC2Connection.run_instances)

Furthermore, `run_instances` takes a few more parameters that `run()` doesn't take:
- `image_id`
- `client_token=None`
- `ebs_optimized=False`
- `network_interfaces=None`

Not taking `image_id` makes sense, since `run()` is called from an `Image` anyway. But I would expect the other parameters to be there. Why aren't they?

**Comment by tobiasmcnulty** [comment]
I also ran into this & would love to see the method signatures synchronized.

**Comment by nchammas** [comment]
At this point you're probably better off moving to boto3. I don't think boto is going to see anything other than critical bug fixes going forward.

**Comment by nchammas** [comment]
Closing this issue since boto is [no longer maintained][1].

[1]: https://github.com/boto/boto/tree/70c65b4f67af41ccfd40d21e49880be568997ba6#deprecation-notice
