### ISSUE TITLE
s3.connect_to_region returns NoneType connection with Location.DEFAULT

### ISSUE THREAD

**Issue by robzienert** [boto/boto#3065]
As the title says, `boto.s3.connect_to_region` will return a NoneType connection if `Location.DEFAULT` is passed as the region. Using `us-east-1` explicitly or any other region works correctly.

This appears to be an issue with passing a blank value.

Version: 2.36.0

See also: https://github.com/ansible/ansible-modules-core/issues/964

**Comment by ch3n2k** [comment]
+1

**Comment by jeremyovc** [comment]
+1

**Comment by splisson-altair** [comment]
+1

**Comment by discordianfish** [comment]
Same for nonexistend regions. Shouldn't it raise an exception instead?

Why is nobody looking at this issue? Seems straightforward to fix and might point to a deeper issue (what fails due to the missing/wrong region which doesn't get handled?))
