### ISSUE TITLE
Unable to paginate RDS instances

### ISSUE THREAD

**Issue by russellballestrini** [boto/boto#3109]
Per the docs I'm supposed to use the marker returned by AWS to get the next page of results however this method only returns a list of objects on the first page and no marker...

```
>>> len(rds.get_all_dbinstances(max_records=100))
21
>>> len(rds.get_all_dbinstances(max_records=20))
20
```

This seems to be the case for many of the boto apis, including #3004 and cache clusters as well.

**Comment by Sodki** [comment]
I think this bug is invalid. You do get a marker if you do

```
rds.get_all_dbinstances(max_records=20).marker
```

And then you can just use that value on subsequent requests. The docs are a bit confusing and an example should be place.

**Comment by russellballestrini** [comment]
Feel free to close, I've moved to boto3 because even though it isn't as user friendly pagination works for the most part out-of-the-box.
