### ISSUE TITLE
get_all_rrsets not filtering on identifier properly.

### ISSUE THREAD

**Issue by krishtk** [boto/boto#3115]
Hi,

I am trying to get the best matched resource record set based on my sni and identifier by passing maxitems as 1. But this always returns me the primary record set even though I have both primary and secondary records.

response = conn.get_all_rrsets(
                zoneid, 'A', sni, sni + '_primary', maxitems=1
            )
response = conn.get_all_rrsets(
                zoneid, 'A', sni, sni + '_secondary', maxitems=1
            )
While creating them I differentiate by the _primary and _secondary for both the records.

But both the responses I am getting are the same.

Any help regarding this matter would be helpful.

Thank you,
Krishna

**Comment by sukrit007** [comment]
I believe https://github.com/boto/boto/commit/33d82c59d1711cafd9ffddb55e3c3062e2f528cc resolves the above issue.  Should work for Boto versions >= 2.33.0
