### ISSUE TITLE
S3 generate signed downloading url is not using response headers

### ISSUE THREAD

**Issue by peterneyens** [boto/boto#3119]
I'm trying to generate a download url for an S3 file/key and want to change the filename when the downloaded file is saved locally (using the Content-Disposition header).
```python
disposition = "attachment; filename=\"{}\"".format(file_name)
response_headers = {
    'response-content-disposition': disposition
}
key.generate_url(60 * 60, query_auth=True, response_headers=response_headers)
```

The [`key.generate_url`](https://github.com/boto/boto/blob/develop/boto/s3/key.py#L629) method uses the [`s3.connection.generate_url_sigv4` method](https://github.com/boto/boto/blob/develop/boto/s3/connection.py#L353) and this function doesn't seem to use the `response_headers` argument, so my Content-Disposition header is not used in the response.

In the normal `s3.connection.generate_url`, the response headers are [added to the query path](https://github.com/boto/boto/blob/develop/boto/s3/connection.py#L397-399) like described in the [S3 documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html#RESTObjectGET-requests-request-parameters).

Kind regards,
Peter

**Comment by joelcox** [comment]
Thanks for this fix @peterneyens.
