### ISSUE TITLE
EMR list_instances filtering by instance_group_types is broken

### ISSUE THREAD

**Issue by markreddy** [boto/boto#3126]
When listing instances using list_instances and providing a filter the response is returned is incorrect. This is caused by using the wrong parameter key (label) InstanceGroupTypeList instead of InstanceGroupTypes as per: http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_ListInstances.html

```python
        if instance_group_types:
            self.build_list_params(params, instance_group_types,
                                   'InstanceGroupTypeList.member')
```
Should be:
```python
        if instance_group_types:
            self.build_list_params(params, instance_group_types,
                                   'InstanceGroupTypes.member')
```

To recreate attempt to list only the MASTER node in an EMR cluster:
```python
from boto.emr.connection import EmrConnection
from boto.ec2.regioninfo import RegionInfo
conn = EmrConnection('access_key', 'secret_key', region=RegionInfo(name='region', endpoint='elasticmapreduce.eu-west-1.amazonaws.com'))
resp = conn.list_instances(cluster_id=clusterId, instance_group_types=["MASTER"])
```
resp will contain all instances in the InstanceGroup and will not be filtered to just the MASTER, as the filter key is not valid.

**Comment by mtdowling** [comment]
PR merged. Closing.
