### ISSUE TITLE
CloudFront API still at version 2010-11-01

### ISSUE THREAD

**Issue by kveroneau** [boto/boto#3165]
I am attempting to use the CloudFront API to perform an "origin" update on an existing distribution.  However, when I attempt to do so, I receive the following unfortunate error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kveroneau/rmenv/lib/python2.6/site-packages/boto/cloudfront/distribution.py", line 368, in update
    self.etag = self.connection.set_distribution_config(self.id, self.etag, new_config)
  File "/home/kveroneau/rmenv/lib/python2.6/site-packages/boto/cloudfront/__init__.py", line 165, in set_distribution_config
    return self._set_config(distribution_id, etag, config)
  File "/home/kveroneau/rmenv/lib/python2.6/site-packages/boto/cloudfront/__init__.py", line 124, in _set_config
    raise CloudFrontServerError(response.status, response.reason, body)
boto.cloudfront.exception.CloudFrontServerError: CloudFrontServerError: 400 Bad Request
<?xml version="1.0"?>
<ErrorResponse xmlns="http://cloudfront.amazonaws.com/doc/2010-11-01/"><Error><Type>Sender</Type><Code>IllegalUpdate</Code><Message>You cannot update the specified distribution using this API version.</Message></Error><RequestId>9192531c-f990-11e4-b6e7-4960d8f60d7f</RequestId></ErrorResponse>

This occurs whenever you call the .update() method on the distribution, regardless what is being changed.  Even if you change nothing, and attempt to perform this method, the same error occurs.

Are there any plans to update the versions of the cloudfront API in boto?  boto is still the officially supported Python SDK for AWS, and it's very disappointing that CloudFront support is broken.

**Comment by Atheryl** [comment]
Same problem here. Any chance to get a reply ?

**Comment by kveroneau** [comment]
I managed to figure out to update CloudFront, but using the botocore package, rather than boto. Here is the basics on how you can update an origin using botocore:

```python
import botocore.session
s = botocore.session.get_session()
cf = s.create_client('cloudfront')
cfg = cf.get_distribution_config(Id='<Distribution Id>')
cfg['DistributionConfig']['Origins']['Items'][0]['DomainName'] = new_origin
cf.update_distribution(Id='<Distribution Id>', DistributionConfig=cfg['DistributionConfig'], IfMatch=cfg['ETag'])
```

I really wish that botocore was better documented, it took me quite awhile to figure this out. Most people online have resorted to the pure REST XML API, and handwriting XML... Come on Amazon, I would expect much better of you.

I posted this here awhile back: https://forums.aws.amazon.com/thread.jspa?messageID=627054&#627054

**Comment by jaraco** [comment]
This issue still exists, and following [this announcement](https://forums.aws.amazon.com/ann.jspa?annID=6697), it seems that boto will be non-functional for CloudFront on June 6. This issue needs to be fixed or at the very least the package README needs to be updated showing that CloudFront is no longer supported.

**Comment by newzhenry** [comment]
Hi, my application currently uses boto 2.48.0 (i.e. Cloudfront version 2010-11-01).  Since version 2010-11-01 will be deprecated, what is the upgrade path? Do I have to use boto3 or is there a simpler alternative? Thank you.
