### ISSUE TITLE
Missing regions for ec2containerservice

### ISSUE THREAD

**Issue by cecton** [boto/boto#3172]
Hello,

I want to use ecs.eu-west-1.amazonaws.com as endpoint for EC2 Container Service but it seems not available by default in [endpoints.json](https://github.com/boto/boto/blob/develop/boto/endpoints.json#L157).

Can I make a PR to add the missing end points?

Best

**Comment by jamesls** [comment]
Fixed in https://github.com/boto/boto/pull/3249
