### ISSUE TITLE
not getting codedeploy connection from ap-southeast-2 region

### ISSUE THREAD

**Issue by cliffano** [boto/boto#3179]
I'm trying to use boto for creating application and deployment group, but I can't get the connection when I use ap-southeast-2 region.

Code snippet:
```
import boto.codedeploy
conn = boto.codedeploy.connect_to_region('ap-southeast-2')
print conn
```

Output:
```
None
```

But if I changed the region to 'us-east-1', then I get the connection properly:
```
CodeDeployConnection:codedeploy.us-east-1.amazonaws.com
```

AWS CodeDeploy is available from ap-southeast-2 according to http://docs.aws.amazon.com/general/latest/gr/rande.html#codedeploy_region

Is there any reason why this is not working with boto?
I'm using the latest boto version 2.38.0

**Comment by cliffano** [comment]
I just had a look at the code, and found out that ap-southeast-2 is not yet configured in endpoints.json .
Will submit a PR for this soon.

**Comment by SydOps** [comment]
Are there any flexible and smart ways to avoid to manually add the site one by one and refer the url [Regions and Endpoints](http://docs.aws.amazon.com/general/latest/gr/rande.html) directly.

**Comment by cliffano** [comment]
Instead of endpoint host like codedeploy.us-east-1.amazonaws.com , I'd recommend using a format codedeploy.{region}.amazonaws.com , or even {service}.{region}.amazonaws.com .

But perhaps there's a reason why boto chose to have a list instead, would be keen to hear from someone who was involved with the decision early on.

**Comment by cliffano** [comment]
Closing this issue  since https://github.com/boto/boto/pull/3180 has been merged.
