### ISSUE TITLE
boto.emr.step.StreamingStep doesn't support -files option

### ISSUE THREAD

**Issue by minhoryang** [boto/boto#3203]
-files option is needed for downloading additional files from s3, mainly for mapper/reducer.

As I expected)
 boto.emr.step.StreamingStep will works as 'Add step' at the cluster details (EMR dashboard).

But)
 boto.emr.step.StreamingStep doesn't handle s3:// location at the mapper and reducer options.

According to the controller log which created at the cluster details page and worked well, mapper and reducer options was relocated at work path, and added 2 files option for moving s3 objects to work path.
```
bash /home/hadoop/bin/hadoop jar /home/hadoop/contrib/streaming/hadoop-streaming.jar -files s3://minhoryang-example/run4/mapper_bi.py,s3://minhoryang-example/reducer_dynamodb.py -mapper mapper_bi.py -reducer reducer_dynamodb.py -input s3://sgcs15spproj5tokyo/count_number.txt -output s3://minhoryang-example/long/out4/
```
So I checked the boto documents and found -cacheFile option and tried.
```syslog
2015-06-01 13:47:58,519 WARN org.apache.hadoop.streaming.StreamJob (main): -cacheFile option is deprecated, please use -files instead.
```

**Comment by minhoryang** [comment]
AMI version:3.7.0
Hadoop distribution:Amazon 2.4.0

**Comment by minhoryang** [comment]
I noticed that I shouldn't remove the -cacheFile option for supporting other versions.

**Comment by minhoryang** [comment]
I tested
```python
add_jobflow_steps('JOBNAME', [StreamingStep("Added", mapper="mapper_bi.py", reducer="reducer_dynamodb.py", action_on_failure="CONTINUE", input="s3://sgcs15spproj5tokyo/count_number.txt", output="s3://minhoryang-example/long/out5", files=["s3://minhoryang-example/run4/mapper_bi.py", "s3://minhoryang-example/reducer_dynamodb.py"])])
```
But failed. (Sorry for failing commit)

Now I realized that need to set -files options before -mapper.
And -step_args was designed like this. :(
Now I confused that do I need to implement -files?

**Comment by minhoryang** [comment]
:(
Is anybody there for helping me?

I tried to use -step_args like:
```
add_jobflow_steps('JOBNAME', [StreamingStep("Added", mapper="mapper_bi.py", reducer="reducer_dynamodb.py", action_on_failure="CONTINUE", input="s3://sgcs15spproj5tokyo/count_number.txt", output="s3://minhoryang-example/long/out6", step_args="-files s3://minhoryang-example/run4/mapper_bi.py,s3://minhoryang-example/reducer_dynamodb.py")])
```

But syslog said:
```syslog
-files s3://minhoryang-example/run4/mapper_bi.py,s3://minhoryang-example/reducer_dynamodb.py
```

**Comment by minhoryang** [comment]
1) python calls -> all failed.
![image](https://cloud.githubusercontent.com/assets/1270855/7915874/5798b028-08bb-11e5-9943-21de1bd230cd.png)

2) Failed status.
![image](https://cloud.githubusercontent.com/assets/1270855/7915905/837c4fce-08bb-11e5-92e4-6bd5f3de24c8.png)

3) the controller log from last tried
![image](https://cloud.githubusercontent.com/assets/1270855/7915919/a13503da-08bb-11e5-840c-5969f5ce5ca5.png)

4) the syslog from last tried
![image](https://cloud.githubusercontent.com/assets/1270855/7915940/c47162bc-08bb-11e5-813b-3a7e23ccf038.png)

4) The magical  commands (which was from above step 3) worked?!
![image](https://cloud.githubusercontent.com/assets/1270855/7915858/433e2ce8-08bb-11e5-8931-2fc62204d326.png)

**Comment by minhoryang** [comment]
![image](https://cloud.githubusercontent.com/assets/1270855/7916143/ebde9a1c-08bc-11e5-9661-2244af908080.png)

the tiny diff founds.

**Comment by minhoryang** [comment]
OMG.... IT WORKS..
```
add_jobflow_steps('JOBNAME', [StreamingStep("Added", mapper="mapper_bi.py", reducer="reducer_dynamodb.py", action_on_failure="CONTINUE", input="s3://sgcs15spproj5tokyo/count_number.txt", output="s3://minhoryang-example/long/out5", step_args=["-files", "s3://minhoryang-example/run4/mapper_bi.py,s3://minhoryang-example/reducer_dynamodb.py"])])
```

worked case:
```
step_args=["-files", "s3://minhoryang-example/run4/mapper_bi.py,s3://minhoryang-example/reducer_dynamodb.py"]
```

failed case:
```
step_args="-files s3://minhoryang-example/run4/mapper_bi.py,s3://minhoryang-example/reducer_dynamodb.py"
```

**Comment by minhoryang** [comment]
I'll close this issue, because of step_args existed.

**Comment by mdonahoe** [comment]
This thread was helpful, thanks!
