### ISSUE TITLE
item.iteritems() fails in Python3.4.3 / boto 2.38.0

### ISSUE THREAD

**Issue by mjdellwo** [boto/boto#3230]
In the boto (2.38.0) scripts  bin/dynamodb_dump and bin/dynamodb_load , there are calls item.iteritems().  However it appears that iteritems() is no longer a dictionary method under Python3, and these calls should be converted to iter(item.items()).  I also see names.iteritems() in the elbadmin script.

I do not know the consequences of changing this for Python2.  I compiled Python 3.4.3 from scratch on RedHat 6 and then did 'pip install boto'.

**Comment by jamesls** [comment]
Fixed via @nishigori in #3231
