### ISSUE TITLE
BatchTable.put_item should not accept overwrite parameter

### ISSUE THREAD

**Issue by bartaelterman** [boto/boto#3243]
The `BatchTable.put_item` method should not accept an `overwrite` parameter. It does not work, and according to [this SO post](http://stackoverflow.com/questions/31026899/boto-dynamodb-how-can-i-prevent-overwriting-items-with-batch-write) the DynamoDB API does not support it.

To avoid confusion, it would be best to remove this parameter.

**Comment by jamesls** [comment]
To avoid breaking backwards compatibility, our best option would be to undocument it and emit a warning if this parameter is used.

**Comment by jamesls** [comment]
Consolidating issues over to #3273 which explains the issue in more detail.
