### ISSUE TITLE
Can't connect using boto.opsworks.connect_to_region: returns None

### ISSUE THREAD

**Issue by laukamp** [boto/boto#3256]
AWS_ACCESS_KEY_ID = ' ... '
AWS_SECRET_ACCESS_KEY = ' ...'

conn = boto.opsworks.connect_to_region('eu-west-1',
                                      aws_access_key_id=AWS_ACCESS_KEY_ID,
                                      aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                                      validate_certs=False)
conn is None
Boto returns None from inside or outside AWS (with or without credentials).

What I'm missing?
Thanks

**Comment by jamesls** [comment]
Opsworks is not available in eu-west-1: http://docs.aws.amazon.com/general/latest/gr/rande.html#opsworks_region

If the service is not available in the specific region, then `connect_to_region` will return None.

Let us know if you have any other questions.

**Comment by mtdowling** [comment]
I'll go ahead and close this. Please let us know if there's anything else you need.

**Comment by laukamp** [comment]
That's right! Thank you very much for your answer!

**Comment by GheloAce** [comment]
Hi Guys, would it be more useful if the `connect_to_region` methods raise an exemption (like 'ServiceUnavailableRegion' or the sorts) instead of `None`.  If so, i'll fort the repo then code it.
