### ISSUE TITLE
How do I presign an object? 

### ISSUE THREAD

**Issue by avinassh** [boto/boto#3261]
I need method for this: [Uploading Objects Using Pre-Signed URLs](http://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html)

Is `generate_url` is the right equivalent? heres what I want:

- generate a URL where client can upload the file/image, with policy of key being `public-read`
- I pass the URL client
- Once client uploads file/image to the URL, he gets back link to the uploaded image 

Also, `generate_url` doesn't seem to accept `policy` parameter. It always fails, if I provide that. Without that, I generated a URL, did curl and uploaded image. Now I can see the image in the bucket. To access it, again I had to generate the URL. 

Appreciate any help. Thanks!

**Comment by jamesls** [comment]
Yes, you have the right method.  If you want to generate a presigned POST you can also use `build_post_form_args`.
