### ISSUE TITLE
`query_auth` is missing details 

### ISSUE THREAD

**Issue by avinassh** [boto/boto#3264]
In the [`generate_url`](http://boto.readthedocs.org/en/latest/ref/s3.html#boto.s3.key.Key.generate_url), every parameter is explained, except `query_auth`

**Comment by stevenbrichards** [comment]
@avanash Are you referring to the documentation?

**Comment by avinassh** [comment]
@stevenbrichards yup!

**Comment by stevenbrichards** [comment]
If you have documentation you'd like to add you can submit a pull request. Or I can take a look at it to add some :)

**Comment by avinassh** [comment]
Nope, I have no idea what does `query_auth` do, that's why I raised an issue here. Please add some info for it :)

**Comment by stevenbrichards** [comment]
Gotcha. I'll see what I can find!

On Wednesday, August 19, 2015, avinassh <notifications@github.com> wrote:

> Nope, I have no idea what does query_auth do, that's why I raised an
> issue here. Please add some info for it :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boto/boto/issues/3264#issuecomment-132883541>.
>


-- 

Steven Richards

Operations & Systems Engineer

Axiom Zen

M*:* +1 604 446 0174

**Comment by stevenbrichards** [comment]
So with a bit of digging it looks like `query_auth` is set by default to `True` and if true adds the details needed to sign the request in the URL (compared to performing this in the header), this actual use of it is below: (as seen in this [file](https://github.com/boto/boto/blob/7789bd00f7428804a8aa07f99c99b0609590520b/boto/s3/connection.py#L411-L415))
```
 if query_auth:
            query_part = '?' + self.QueryString % (encoded_canonical, expires,
                                                   self.aws_access_key_id)
 else:
            query_part = ''
```
This follows the standard practice as seen [here](http://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html).
> Query string parameters. You can add the signature as a query string value to the request. Because the request signature is part of the URL, this type of URL is referred to as a pre-signed URL.

I'll go ahead and add some info to the source and submit a PR. 

Thanks for pointing this out!

**Comment by stevenbrichards** [comment]
Fixed in: https://github.com/boto/boto/pull/3308

Labels: S3, Documentation

**Comment by kyleknap** [comment]
Merged pull request. Closing issue.

**Comment by avinassh** [comment]
@stevenbrichards thanks! :)
