### ISSUE TITLE
Unable to run describe_stacks()

### ISSUE THREAD

**Issue by xgt001** [boto/boto#3274]
![image](https://cloud.githubusercontent.com/assets/1500199/8717716/8e1b3b98-2bbb-11e5-8b4f-2f13fcb2be63.png)

I am unable to run stack.describe_stacks().

Looks like boto is not providing node name correctly? I am not sure about the exact issue here. Please let me know if the problem is on my end.

**Comment by jamesls** [comment]
To help troubleshoot, we'd need to know the specific error message.  What's the specific error message you're getting?  I'm not able to repro this issue, the describe_stacks() call works for me.

**Comment by xgt001** [comment]
@jamesls This was not a Boto issue, but this was due to internet connectivity issues on my end (had some dns issues). However, I think we could use better logging to indicate connectivity issues (when 10  retries fail we are logging this as a boto issue). 
I reported the issue because connect_opsworks() was working fine.
 If you want to close the issue as non issue please feel free to do so.

**Comment by jamesls** [comment]
Great.  I'm glad you were able to get this working.  It would be helpful to see what the full error message is.  I'm going to close this for now, but if you want to share what the original error message is vs. what you'd like it to be we can reopen this issue.
