### ISSUE TITLE
AWS GovCloud support for Cloudtrail

### ISSUE THREAD

**Issue by gburiola** [boto/boto#3277]
CloudTrail has been available in GovCloud since Dec 16, 2014

http://aws.amazon.com/about-aws/whats-new/2014/12/16/aws-cloudtrail-is-now-available-in-the-aws-govcloud-us-region/

http://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html

**Comment by stevenbrichards** [comment]
Can be closed, PR has been merged
