### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by alkemrebecca** [boto/boto#3284]
installed: python 2.7.6, boto

i am having this error:

Traceback (most recent call last):
File "/s3-parallel-put", line 410, in 
sys.exit(main(sys.argv))
File "/s3-parallel-put", line 381, in main
bucket = connection.get_bucket(options.bucket)
File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 503, in get_bucket
return self.head_bucket(bucket_name, headers=headers)
File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 522, in head_bucket
response = self.make_request('HEAD', bucket_name, headers=headers)
File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 665, in make_request
retry_handler=retry_handler
File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
retry_handler=retry_handler)
File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
raise ex
socket.gaierror: [Errno -2] Name or service not known

May i know how to resolve it?
Thanks.

**Comment by stevenbrichards** [comment]
What version of boto is this? are you still experiencing this consistently?

**Comment by alkemrebecca** [comment]
boto 2.38.0
This error has been since from the start.

Please let me know if it can be resolve.
Thanks.

**Comment by stevenbrichards** [comment]
Thanks @alkemrebecca can you also share the snippet of code you're using to cause this?

**Comment by stevenbrichards** [comment]
Labels: Needs more info, Unconfirmed, S3

**Comment by alkemrebecca** [comment]
Hi Steven,

I got the s3-parallel-put file from this link:
https://github.com/twpayne/s3-parallel-put

**Comment by stevenbrichards** [comment]
@alkemrebecca thanks! and what are you supplying for the bucket-name? That type of error comes from failing to look up and resolve a hostname. so if it was trying to connect to something like "not-a-real-s3-bucket.s3.amazonaws.com" it would fail like that.

**Comment by alkemrebecca** [comment]
I believed i have used the correct authentication information as i am able to connect using s3cmd and done transfer successfully.

**Comment by stevenbrichards** [comment]
Ok, I'm not sure what I can do here as I don't have much information. The issue may lie in `s3-parallel-put` and how they use the boto SDK. You can try to do the following in python yourself to make sure boto can connect to your bucket:
```
>>> import boto
>>> conn = boto.s3.connect_to_region('<region of your bucket>')
>>> conn.get_bucket('<name of your bucket>')
```

**Comment by alkemrebecca** [comment]
I've tried and able to retrieve the bucket successfully.

**Comment by stevenbrichards** [comment]
Ok, then you should go ahead and open an issue with the developer of `s3-parallel-put`.

**Comment by alkemrebecca** [comment]
Thanks.
However I got the response below:
https://github.com/twpayne/s3-parallel-put/issues/21

I am not sure who to approach now.

**Comment by stevenbrichards** [comment]
If the develop of s3-parallel-put doesn't want to support their own software then there isn't much else you can do.

**Comment by alkemrebecca** [comment]
Well, it seems so.
Thanks so much.

**Comment by mikeatlas** [comment]
@alkemrebecca see https://github.com/twpayne/s3-parallel-put/pull/23

**Comment by mjafar1** [comment]
I was getting the same error. I found
http://blog.chillidogsoftware.com/2013/03/28/fix-for-name-or-service-not-known-error-with-boto/
creating calling format object as in
calling_format=boto.s3.connection.OrdinaryCallingFormat()
and passing it to the connection ctor/init fixed the issue for me

**Comment by jseabold** [comment]
Is the default for the calling format platform or otherwise system or locale dependent? I have code that works on one machine and not another without setting the calling format.

**Comment by alkemrebecca** [comment]
you can try this script instead. it solved my problem as it was the location problem.
https://github.com/weftio/s3-parallel-put/blob/d0aaf13e1ec9213877679c08813469b1678353d7/s3-parallel-put#L382
