### ISSUE TITLE
Boto doesn't recognize `AWS_DEFAULT_PROFILE`

### ISSUE THREAD

**Issue by sesas** [boto/boto#3287]
From: https://github.com/boto/boto/issues/2988
aws cli docs: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment

Boto doesn't recognize `AWS_DEFAULT_PROFILE` env var as the aws cli does, creating confusion when using a mix of aws cli and boto scripts.

**Comment by jamesls** [comment]
The CLI was the only tool to use AWS_DEFAULT_PROFILE, so we instead updated the CLI to support `AWS_PROFILE`.

**Comment by sesas** [comment]
So what happens when both are provided?  which one takes precedence?

**Comment by jamesls** [comment]
`AWS_DEFAULT_PROFILE` takes precedence in the CLI, primarily for backwards compatibility reasons.

**Comment by berdario** [comment]
I think the official docs might need to be updated, then:

http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment


(on my system neither `AWS_DEFAULT_PROFILE` nor `AWS_PROFILE` are actually picked up... but I'm stil trying to pin down the issue)
