### ISSUE TITLE
Boto Truck Factor

### ISSUE THREAD

**Issue by gavelino** [boto/boto#3296]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Boto** and obtained a value of **4**.

The developers responsible for this TF are:

Mitch Garnaat - author of 39% of the files
Daniel Lindsley - author of 13% of the files
James Saryerwinnie - author of 12% of the files
Daniel G. Taylor - author of 9% of the files

To validate our results, we would like to ask **Boto** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Boto**?

(b) Do you agree that **Boto** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Boto** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by jamesls** [comment]
I'm not sure how much help I can be but:

a) If you want the current maintainers it might be best to look at who's been merging the latest commits
b) no, there are many other people that can step in.
c) unsure
