### ISSUE TITLE
Boto CRC check failed 

### ISSUE THREAD

**Issue by kashifusmani** [boto/boto#3312]
I am using Python 2.7.9 on my test cluster, boto.Version=2.34.0 where , after downloading the file from S3 I am getting the following error message

CRC check failed 0xc77adc6a != 0x6dffac88L
I am creating the connection via
`  conn = S3Connection(aws_access_key, aws_secret_access_key,
                            calling_format=boto.s3.connection.OrdinaryCallingFormat())`
Please note that on my Mac, I have python 2.7.5, boto.Version=2.33.0 and everything worked just fine. I even did not have to pass `calling_format` and the default worked fine.
Looks like the upgrade boto version has something wrong?
Need help.

**Comment by stevenbrichards** [comment]
Hi @kashifusmani,
If I understand correctly you said that you're getting the error on 2.33 and it works fine on 2.34? That would make me think the issue has been patched between those versions, in which case the solution would be to upgrade from 2.33 to 2.34

**Comment by kashifusmani** [comment]
Sorry, that was a type in the question. It works on 2.33 and not on 2.34

**Comment by stevenbrichards** [comment]
Ahh ok thanks!
Can you run the same code with a higher debug level in boto and paste the logs? https://code.google.com/p/boto/wiki/BotoConfig#Boto

**Comment by kashifusmani** [comment]
Ok, never mind. It looks like the CRC check failures are stemming from gzip.GzipFile library. After I am done downloading .dat.gz file from s3, I need to unzip it before processing and hence the error. Do you know whats python recommended library to unzip?

**Comment by stevenbrichards** [comment]
For unzipping a gzip file with python you can use the gzip library : https://docs.python.org/2/library/gzip.html
