### ISSUE TITLE
boto3 pypi indicates developer preview, AWS docs indicate released

### ISSUE THREAD

**Issue by mpdehaan** [boto/boto#3336]
https://pypi.python.org/pypi/boto

"The next major version of Boto is currently in developer preview and can be found in the Boto 3 repository and installed via pip. It supports the latest service APIs and provides a high-level object-oriented interface to many services."

vs

https://aws.amazon.com/sdk-for-python/

**Comment by jamesls** [comment]
This has been updated on our dev branch, but pypi is using the README from the last boto release earlier this year.  This will be updated on pypi once we do a boto release.  Don't have a specific ETA for the next boto release though.
