### ISSUE TITLE
How to specify a timeout for only DynamoDB connections?

### ISSUE THREAD

**Issue by djsmith42** [boto/boto#3347]
I am aware of the `http_socket_timeout` setting in `boto.cfg`, but what if I want to specify a timeout that only applies to my DynamoDB connections, e.g., by passing `timeout=5.0` to `boto.dynamodb2.connect_to_region()`.

This doesn't seem to be possible now, and based on my reading of the code, it won't pass along a timeout value to the underlying connection object.

Am I missing something?

**Comment by komuW** [comment]
@djsmith42 

import boto3

dynamodb = boto3.resource('dynamodb',
                   region_name='DYNAMO_DB_REGION_NAME',
                   endpoint_url='DYNAMO_DB_ENDPOINT_UR'L,
                   aws_access_key_id='ACCESS_KEY',
                   aws_secret_access_key='SECRET_KEY',
                   aws_session_token='SESSION_TOKEN',
                )
dynamodb.meta.client.meta.config.connect_timeout = 12
dynamodb.meta.client.meta.config.read_timeout = 14

**Comment by djsmith42** [comment]
Thanks very much @komuW!

**Comment by komuW** [comment]
you are welcome @djsmith42 . I'm sure there's an easier way of getting to the config object without going through all that .meta objects but I didn't have time to check them out.
