### ISSUE TITLE
Cloudsearch connecting to regions with connect_cloudsearch and lookup issues

### ISSUE THREAD

**Issue by sergioisidoro** [boto/boto#3384]
Region missing from ```connect_cloudsearch``` and ```connect_cloudsearch2```

```cloudsearch.connect_to_region``` wont work, as it will output:

 ```'Layer1' object has no attribute 'lookup'```

region can still be passed in the kwargs of ```connect_cloudsearch```, but it's not such an elegant solution (what I ended up doing):

```
from boto.ec2 import get_region
region = get_region('eu-west-1')
connection = boto.connect_cloudsearch(region=region)
```

boto==2.38.0

Code references:
https://github.com/boto/boto/blob/d9e5cfe900e1a58717e393c76a6e3580305f217a/boto/__init__.py#L647
https://github.com/boto/boto/blob/d9e5cfe900e1a58717e393c76a6e3580305f217a/boto/__init__.py#L665

*Edit:*
Even the solution presented above assumes the service version configuration. Otherwise you'll get:
```The requested version (2011-02-01) of service AmazonEC2 does not exist```

*Edit2*:
Slightly better solution:
```
        rs = boto.cloudsearch.regions()

        for r in rs:
            if r.name == AWS_REGION:
                region = r
                break

        self.connection = boto.connect_cloudsearch(
            region=region
        )
```

**Comment by jamesls** [comment]
Fixed via: https://github.com/boto/boto/pull/3491
