### ISSUE TITLE
No support for multiple s3 lifecycle transitions

### ISSUE THREAD

**Issue by ryansydnor** [boto/boto#3402]

**Comment by ryansydnor** [comment]
This is addressed by https://github.com/boto/boto/pull/3431

**Comment by anonymuse** [comment]
Nice, I'd like to see this implemented. I'll take a look at the related commits.

**Comment by anonymuse** [comment]
Now that #3431 is back working in the CI, this looks gtg.

**Comment by jamesls** [comment]
Fixed via https://github.com/boto/boto/pull/3431
