### ISSUE TITLE
python 3.5 support

### ISSUE THREAD

**Issue by anupamme** [boto/boto#3413]
I am not able to use boto in python 3.5.

boto version: boto==2.38.0 (installed using sudo pip3.5 install boto)

output of uname -a:

Linux instance-8 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linu

when I do import boto I get following error:

Exception: unsupported operand type(s) for +=: 'NoneType' and 'str' ; None ; ('*.py',)
args: (None, '*.py')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/usr/lib/python3/dist-packages/boto/plugin.py", line 92, in load_plugins
    for file in glob.glob(os.path.join(directory, '*.py')):
  File "/usr/lib/python3.5/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 144, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

Can anyone help?

**Comment by anupamme** [comment]
Am I supposed to use boto3 (https://github.com/boto/boto3) instead of boto for python 3.5?

**Comment by jamesls** [comment]
Interesting, I'm not seeing any issues on python3.5.

```
>>> import sys
>>> sys.version
'3.5.0 (default, Oct  1 2015, 17:42:45) \n[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]'
>>> import boto
>>> boto.connect_ec2().get_all_instances()
[Reservation:r-abc]
```

It looks like the line above is failing when it tries to load boto plugins.  I'd check the contents of `~/.boto` as well as `/etc/boto` and see if you have a `[Plugins]` section (and comment it out if so).

To answer your other question, I'd highly recommend using boto3, especially if you're starting a new project.

**Comment by anupamme** [comment]
Commenting out [Plugins] worked for me.

Well I am using a 3rd party project (smart_open) which uses boto. Since that was not working I was considering porting smart_open to use boto3. But now it is not necessary.

**Comment by anonymous31173** [comment]
the best option if you have boto==2.38.0 is to "**pip update boto**" then you have boto==2.<latest>.0
