### ISSUE TITLE
[Feature Request] - Add support for encrypted EBS boot volumes

### ISSUE THREAD

**Issue by ryansydnor** [boto/boto#3427]
Encrypted EBS boot volumes were recently [announced](https://aws.amazon.com/blogs/aws/new-encrypted-ebs-boot-volumes/).

I could imagine [copy_image](https://github.com/boto/boto/blob/d9e5cfe900e1a58717e393c76a6e3580305f217a/boto/ec2/connection.py#L4408) taking in the two new parameters 'encrypted' and 'kmsKeyID'. And, of course, propagating those through to [CopyImage](https://github.com/boto/boto/blob/d9e5cfe900e1a58717e393c76a6e3580305f217a/boto/ec2/image.py#L435)

**Comment by jamesls** [comment]
Fixed in https://github.com/boto/boto/pull/3438
