### ISSUE TITLE
Die when run on Python 3

### ISSUE THREAD

**Issue by xiongchiamiov** [boto/boto#3434]
Related to #3433, it seems to me that while Python 3 isn't supported, it'd be wonderful from a user perspective to get an early exception indicating that when trying to run boto under py3.

**Comment by xiongchiamiov** [comment]
Heck, even changing the `setup.py` to not say that py3 is supported (while the README says it isn't!) would be great.

**Comment by jamesls** [comment]
Boto supports python3.  Let's track the current python3 issues for the INI config file parsing over in #3433.  If there's other specific cases you're running into in python3, we'll track those down.  Please feel free to open any other issues you run into with python3.

**Comment by xiongchiamiov** [comment]
Will do, thanks.
