### ISSUE TITLE
Please release 2.38.1 or 2.39 of good old boto

### ISSUE THREAD

**Issue by yarikoptic** [boto/boto#3435]
I know that the main accent is given to boto3 development, but there is a good number of problems fixed since 2.38.0, so it would be very beneficial to the community if new bugfix release was furnished.

Thanks in advance!

**Comment by jamesls** [comment]
Feedback heard.  I'm going to first try to see what's been going on with the latest round of travis CI failures for py3 and make sure we can get clean test passes.

**Comment by snordhausen** [comment]
+1 for a new release

Just this week, I stumbled over two known bugs in the current release.

**Comment by Solyony** [comment]
+1 for a new release.

**Comment by nishigori** [comment]
+1

**Comment by mtdowling** [comment]
Version 2.3.90 was released a few days ago: https://github.com/boto/boto/releases/tag/2.39.0
