### ISSUE TITLE
SQS connection get_queue failed in China region

### ISSUE THREAD

**Issue by chenziliang** [boto/boto#3440]
I use the following code to get queue in China region, conn.get_queue return None always. The debug information shows "Bad Request". conn.get_all_queues() worked. Any idea about the issue ?
Thanks !

```
conn = boto.sqs.connect_to_region(
    "cn-north-1", aws_access_key_id=key_id, aws_secret_access_key=secret_key, debug=2)
q = conn.get_queue("my_queue_name")
```

send: 'GET /?Action=GetQueueUrl&QueueName=cloudtrail-bj&Version=2012-11-05 HTTP/1.1\r\nAccept-Encoding: identity\r\nContent-Length: 0\r\nHost: cn-north-1.queue.amazonaws.com.cn\r\nAuthorization: AWS4-HMAC-SHA256 Credential=yyyyyyyyy/20151222/cn-north-1/sqs/aws4_request,SignedHeaders=host;x-amz-date,Signature=xxxxxxxxxx\r\nX-Amz-Date: 20151222T140256Z\r\nUser-Agent: Boto/2.38.0 Python/2.7.10 Darwin/14.5.0\r\n\r\n'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: x-amzn-RequestId: c0b20366-324e-5054-be6c-4d95681e72c2
header: Content-Type: text/xml
header: Content-Length: 343

**Comment by jamesls** [comment]
I'm not seeing that issue.  I'd try using `boto.sqs.connect_to_region('cn-north-1')`.  Here's what I tried:

```
import boto.sqs
import boto
s = boto.sqs.connect_to_region('cn-north-1')
print(s.get_queue('TestQ'))

# prints:
Queue(https://cn-north-1.queue.amazonaws.com.cn/12345/TestQ)
```

**Comment by chenziliang** [comment]
Look like it is a permission issue, but AWS reported 400 which is confusing.
