### ISSUE TITLE
No support for NAT gateways

### ISSUE THREAD

**Issue by xiaclo** [boto/boto#3443]
Maybe I'm just missing it, but I'm not seeing anywhere to create or assign NAT gateways to a VPC.

Not NAT EC2 instances, but the Amazon-managed ones.

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat-gateway.html

**Comment by Brett55** [comment]
I couldn't find it either in boto 2x.

**Comment by wholroyd** [comment]
Just pushed for review in https://github.com/boto/boto/pull/3472

**Comment by rcsavage** [comment]
AWS should not be releasing services without first adding it to the SDKs... what a PITA.

**Comment by dkavanagh** [comment]
+1

**Comment by JordonPhillips** [comment]
We are no longer providing service updates to boto 2.x, for additional features please use boto3, which can be used in conjunction with boto 2.x if necessary. [Here](http://boto3.readthedocs.org/en/latest/reference/services/ec2.html#EC2.Client.create_nat_gateway)'s the boto3 docs for creating a NAT Gateway, the other related functions are also on that page.
