### ISSUE TITLE
ec2.connect_to_region fails to return EC2Connection for new ap-northeast-2 region

### ISSUE THREAD

**Issue by hrez** [boto/boto#3457]
ec2.connect_to_region fails to return EC2Connection for new ap-northeast-2 region

```
ipdb> pp ec2.connect_to_region('ap-northeast-2')
None
ipdb> pp ec2.connect_to_region('ap-northeast-1')
EC2Connection:ec2.ap-northeast-1.amazonaws.com
ipdb> pp boto.__version__
'2.38.0'
ipdb> 
```

**Comment by stevemac007** [comment]
I had the same issue and created #3454 to fix that and the rest of the supported services in ap-northeast-2

**Comment by chongkong** [comment]
Similar issue here, I couldn't connect to s3 bucket in Seoul region with 400 Bad Request error. Eagerly waiting for updates #3454

**Comment by kyleknap** [comment]
Just merged the reference PR. Will be available in the subsequent release. Closing issue.

**Comment by sesas** [comment]
When is the next release scheduled?
