### ISSUE TITLE
Auto Scaling Describe Notification Configurations call is missing

### ISSUE THREAD

**Issue by onema** [boto/boto#3484]
I look through the code and the docs but this call is missing in boto. Is this correct? Or does it have a different name?

This is the API call in question [Describe Notification Configurations](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_DescribeNotificationConfigurations.html)

**Comment by JordonPhillips** [comment]
We are no longer providing service updates to boto 2.x, for additional features please use boto3, which can be used in conjunction with boto 2.x if necessary. [Here](http://boto3.readthedocs.org/en/latest/reference/services/autoscaling.html#AutoScaling.Client.describe_notification_configurations)'s that operation in the boto3 docs.
