### ISSUE TITLE
S3 get_contents methods don't retry on InternalError

### ISSUE THREAD

**Issue by bbayles** [boto/boto#3493]
Our team has been encountering a problem in which some files we retrieve with boto's `get_contents_to_filename` method are incomplete. Everything seems to finish downloading properly, but only part of the file is retrieved.

We found in our S3 bucket logs lines that indicate the server is having a problem; they include the string `InternalError`:

```
... REST.GET.OBJECT prefix/name.ext "GET /bucket/prefix/name.ext?versionId=... HTTP/1.1" 200 InternalError
```

You can see that a `200` response code is logged, and that seems to be why boto does not notice that there is a problem.

If the [`open_read` method](https://github.com/boto/boto/blob/develop/boto/s3/key.py#L300-L303) could detect the `InternalError` it could raise an exception and kick off the normal retrying process.

I would submit a pull request with a test case, but I can't tell from the [S3 bucket logs format](http://docs.aws.amazon.com/AmazonS3/latest/dev/LogFormat.html) where the `InternalError` is appearing. It's in the `Error Code` section of the entry.

Thoughts:
- This should be fixed server-side; 200 is not an appropriate code here.
- If this can happen (it has been for multiple weeks) boto should detect it and retry

**Comment by thanosd** [comment]
I'm getting the same thing. Once every 100k requests or so, I'll get a failure in the logs, but boto just returns partial data. @bbayles: is this happening any more frequently for you?

**Comment by bbayles** [comment]
@thanosd, we eventually implemented a retrying scheme to get around this issue. I haven't noticed an increase in frequency. I've only had this issue in us-east-1.
