### ISSUE TITLE
Broken Repository

### ISSUE THREAD

**Issue by TripleDogDare** [boto/boto#3507]
You may run `git fsck` in a checked out repository to confirm if you do not have fsck on checkout enabled.
```
git clone git@github.com:boto/boto.git
Cloning into 'boto'...
remote: Counting objects: 41882, done.
error: object c1eddff4ee3f62b6039f1083651b9118883e7f07:invalid author/committer line - bad time zone
fatal: Error in object
fatal: index-pack failed
```

**Comment by JordonPhillips** [comment]
What version of git are you using? I haven't had any trouble pulling the repo (though I do get the warning you mention).

**Comment by TripleDogDare** [comment]
I'm using 1.9.1

**Comment by jamesls** [comment]
I see the same thing, but from what I can tell fixing this will require rebasing/force pushing to master which isn't feasible.

If there's a way to fix this without force pushing master, I'd be open to it. Otherwise, I don't think there's anything we can do.

**Comment by faltrock-abone** [comment]
Ran into this while trying to build electron. Problem was having `transfer.fsckobjects = true` in my `.gitconfig`.

**Comment by bfontaine** [comment]
>  Problem was having `transfer.fsckobjects = true` in my `.gitconfig`.

The problem is the repo, not the check. I have the same issue; I can temporarily remove that check in order to clone `boto` but it doesn’t fix the repo issue.
