### ISSUE TITLE
cloudtrail does not support multi-region trail

### ISSUE THREAD

**Issue by mlosapio** [boto/boto#3514]
Update needs to be made that supports multi-region trails. 

From docs: 
    "IsMultiRegionTrail": boolean,

**Comment by JordonPhillips** [comment]
We are no longer providing service updates to boto 2.x, for additional features please use [boto3](http://boto3.readthedocs.org/en/latest/reference/services/cloudtrail.html#CloudTrail.Client.create_trail), which can be used in conjunction with boto 2.x if necessary.
