### ISSUE TITLE
MWS GetCompetitivePricingForASIN response not parsing NumberOfOfferListings correctly.

### ISSUE THREAD

**Issue by dawats** [boto/boto#3557]
The raw XML returned from MWS contains `NumberOfOfferListings ` which is a list of the different conditions the product is sold for and the number of sellers for each condition.

Here's the relevant snippet:

```
<NumberOfOfferListings>
    <OfferListingCount condition="New">
        109
    </OfferListingCount>
    <OfferListingCount condition="Collectible">
        1
    </OfferListingCount>
    <OfferListingCount condition="Used">
        55
    </OfferListingCount>
    <OfferListingCount condition="Any">
        165
    </OfferListingCount>
</NumberOfOfferListings>
```
However, when Boto parses `NumberOfOfferListings` something goes wrong because it returns a list containing an empty string, and a new attribute: `OfferListingCount` is added that only contains one of the conditions.

The parsed response:

```
CompetitivePricing{}(
    NumberOfOfferListings: [''], 
    OfferListingCount: 165{'condition': 'Any'}
)
```
Example: Test Code. Boto 2.40, Python 3.5
I've chosen a book that has offers for both `used` and `new` conditions.

```
from boto.mws import connection
conn = connection.MWSConnection(aws_access_key_id=access_key,
                                             aws_secret_access_key=secret_key,
                                             Merchant=merchant_id)
response = conn.get_competitive_pricing_for_asin(MarketplaceId=marketplace_id,
                                                                  ASINList=['0544609719'])
```

***
The problem seems to be here: https://github.com/boto/boto/blob/develop/boto/mws/response.py#L522

I have tried playing around with some monkey-patching but I can't get the desired outcome, which would be a list of `OfferListingCount` objects. One for each condition, with the number of offers per condition.

```
class OfferListingCount(ResponseElement):
    pass

CompetitivePricing.NumberOfOfferListings = Element(OfferListingCount=ElementList(OfferListingCount))

```
Gets me all the conditions but without the offer counts:

```
CompetitivePricing{}(
    NumberOfOfferListings: ^NumberOfOfferListings^{}(
        OfferListingCount: [
            OfferListingCount{'condition': 'New'}(), 
            OfferListingCount{'condition': 'Collectible'}(), 
            OfferListingCount{'condition': 'Used'}(), 
            OfferListingCount{'condition': 'Any'}()]
    ), 
)
```

**Comment by dawats** [comment]
This is the monkey patch I finally came up with:

```
class OfferListingCount(ResponseElement):
    OfferCount = 0

    def endElement(self, name, value, connection):
        self.OfferCount = value
        super(OfferListingCount, self).endElement(name, value, connection)

CompetitivePricing.NumberOfOfferListings = Element(OfferListingCount=ElementList(OfferListingCount))
```

Which gives me the output I want:

```
CompetitivePricing{}(
    NumberOfOfferListings: ^NumberOfOfferListings^{}(
        OfferListingCount: [
            OfferListingCount{'condition': 'New'}(OfferCount: '105'), 
            OfferListingCount{'condition': 'Collectible'}(OfferCount: '2'), 
            OfferListingCount{'condition': 'Used'}(OfferCount: '58'), 
            OfferListingCount{'condition': 'Any'}(OfferCount: '165')]
    )
)
```

**Comment by disruptek** [comment]
I'm sorry for the delay; I've been traveling.

You can make queries and parse responses using whatever custom parser you wish, so monkey patching isn't necessary -- simply inherit the existing parser and reimplement.

However, it seems to me that your change is a bugfix.  How do you feel about submitting a patch?

**Comment by disruptek** [comment]
Fixed in my branch using normal `ComplexType` semantics; you access the value as `.Value` and the condition as `.condition`.  The value is cast to an integer and there's a pretty string representation with the quantity and condition.

**Comment by tlykken** [comment]
I am having this same issue.  Whatever was committed by disruptek doesn't appear to have made it into v2.48.

Does anyone know what the fix for this is?
