### ISSUE TITLE
boto ec2: how to get region name from instance ID ?

### ISSUE THREAD

**Issue by longk15t** [boto/boto#3606]
Hi,

I found out that I can't get any attributes of an instance without using `connect_to_region`. How can I get region name e.g 'us-west-1', 'ap-southeast-2' from just an instance ID (i-xxxxxx) ? 

Thanks for help.

**Comment by longk15t** [comment]
any help ?

**Comment by longk15t** [comment]
ping anyone.

**Comment by jmehnle** [comment]
You can't, because instance IDs are relative to the region. The same instance ID could exist in multiple regions. Your best bet is to connect to all regions you have instances in and see if your instance ID exists there.
