### ISSUE TITLE
[Errno 8] nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by RandallShane** [boto/boto#3614]
While the awscli interface allows operation, the same functionality does not exist in both.  Environment is OS X, Python 2.7.10, boto 2.42.0

Reproduce with the following:

from boto.s3.connection import S3Connection
from boto.s3.key import Key

access_key = '...'
access_secret = '...'
bucketname = '...'

conn = S3Connection(access_key, access_secret)
b = conn.get_bucket(bucketname, validate=False)
k = Key(b)
k.key = 'Hello'
k.set_contents_from_string("Hello World")

Resulting error is as follows:

---

gaierror                                  Traceback (most recent call last)
<ipython-input-11-e2442d272124> in <module>()
----> 1 k.set_contents_from_string("Hello World")

/Library/Python/2.7/site-packages/boto/s3/key.pyc in set_contents_from_string(self, string_data, headers, replace, cb, num_cb, policy, md5, reduced_redundancy, encrypt_key)
   1424         r = self.set_contents_from_file(fp, headers, replace, cb, num_cb,
   1425                                         policy, md5, reduced_redundancy,
-> 1426                                         encrypt_key=encrypt_key)
   1427         fp.close()
   1428         return r

/Library/Python/2.7/site-packages/boto/s3/key.pyc in set_contents_from_file(self, fp, headers, replace, cb, num_cb, policy, md5, reduced_redundancy, query_args, encrypt_key, size, rewind)
   1291             self.send_file(fp, headers=headers, cb=cb, num_cb=num_cb,
   1292                            query_args=query_args,
-> 1293                            chunked_transfer=chunked_transfer, size=size)
   1294             # return number of bytes written.
   1295             return self.size

/Library/Python/2.7/site-packages/boto/s3/key.pyc in send_file(self, fp, headers, cb, num_cb, query_args, chunked_transfer, size)
    748         self._send_file_internal(fp, headers=headers, cb=cb, num_cb=num_cb,
    749                                  query_args=query_args,
--> 750                                  chunked_transfer=chunked_transfer, size=size)
    751
    752     def _send_file_internal(self, fp, headers=None, cb=None, num_cb=10,

/Library/Python/2.7/site-packages/boto/s3/key.pyc in _send_file_internal(self, fp, headers, cb, num_cb, query_args, chunked_transfer, size, hash_algs)
    949             headers,
    950             sender=sender,
--> 951             query_args=query_args
    952         )
    953         self.handle_version_headers(resp, force=True)

/Library/Python/2.7/site-packages/boto/s3/connection.pyc in make_request(self, method, bucket, key, headers, data, query_args, sender, override_num_retries, retry_handler)
    666             data, host, auth_path, sender,
    667             override_num_retries=override_num_retries,
--> 668             retry_handler=retry_handler
    669         )

/Library/Python/2.7/site-packages/boto/connection.pyc in make_request(self, method, path, headers, data, host, auth_path, sender, override_num_retries, params, retry_handler)
   1069                                                     params, headers, data, host)
   1070         return self._mexe(http_request, sender, override_num_retries,
-> 1071                           retry_handler=retry_handler)
   1072
   1073     def close(self):

/Library/Python/2.7/site-packages/boto/connection.pyc in _mexe(self, request, sender, override_num_retries, retry_handler)
   1028             raise BotoServerError(response.status, response.reason, body)
   1029         elif ex:
-> 1030             raise ex
   1031         else:
   1032             msg = 'Please report this exception as a Boto Issue!'

gaierror: [Errno 8] nodename nor servname provided, or not known

**Comment by chadsaun** [comment]
I have this same error when calling `set_contents_from_string`

**Comment by RandallShane** [comment]
I think this either solved itself at some point or just became moot!
