### ISSUE TITLE
Release 2.47?

### ISSUE THREAD

**Issue by houglum** [boto/boto#3718]
We'd like to have the changes from https://github.com/boto/boto/pull/3691 included in a release of Boto so that we can add XML support for per-object-storage-class to gsutil; gsutil is pip-installable, so we need a specific version to depend on, rather than HEAD on GitHub :) We've also seen a couple folks complain about the lack of storage class handling when trying to use Boto - https://github.com/boto/boto/issues/3666, for example.

@JordonPhillips or @kyleknap (as you've done the past few releases), would you mind bumping Boto to 2.47 when you get the chance? Thanks!

**Comment by houglum** [comment]
Friendly ping! If you're unable to do so this week, an ETA would be helpful :)

**Comment by JordonPhillips** [comment]
I can't give a specific date, but I've added this to our backlog!

**Comment by houglum** [comment]
Thanks!

+@royalpeasantry -- we should be able to get your test change from #3729 into v2.47.

**Comment by royalpeasantry** [comment]
That would be great.  Mike is OOO till tomorrow, so it probably won't make it in before then.

**Comment by royalpeasantry** [comment]
The fix is in, ready for 2.47 whenever.  Thanks!

**Comment by JordonPhillips** [comment]
All done!
