### ISSUE TITLE
Boto support for SQS fifo

### ISSUE THREAD

**Issue by vladwoguer** [boto/boto#3788]
I'm trying to send a message for a FIFO queue:
   conn = boto.sqs.connect_to_region(aws_region, aws_access_key_id=aws_access_key_id,
                                          aws_secret_access_key=aws_secret)
        queue = conn.get_queue(aws_queue)
        conn.send_message(queue,'test')
And receiving the following error:
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>MissingParameter</Code><Message>The request must contain the parameter MessageGroupId.</Message><Detail/></Error><RequestId>ID_HERE</RequestId></ErrorResponse>

How can I set the MessageGroupId paramenter?

**Comment by vladwoguer** [comment]
In case anyone has the same doubt, I recommend migrate to boto3.
It's not possible manage SQS fifo queues with boto2. In case anyone find a workaround please let me  know.

**Comment by tirupathiraop** [comment]
Did you find the workaround?

**Comment by vladwoguer** [comment]
No I migrated to boto3, sorry.
