### ISSUE TITLE
Please make a release due to Python 2/3 issues (no new development needed)

### ISSUE THREAD

**Issue by bradyhunsaker** [boto/boto#3896]
I know that new development effort is directed at boto3.

boto already corrects some Python 2/3 issues at *head* but not in any release. I am particularly thinking of #3856, which affects me.

Packages should switch dependence from boto to boto3, but in the meantime it would be good if the compatibility changes in boto are available in an actual release. In the present situation, users affected by some Python 2/3 issues must manually install at head.

**Comment by kdaily** [comment]
Hi there,

This package is deprecated and no longer supported. Please review the deprecation notice for migration to `boto3`. Thanks!

https://github.com/boto/boto#deprecation-notice
