### ISSUE TITLE
Update list of endpoints for SES

### ISSUE THREAD

**Issue by alasdairnicol** [boto/boto#3899]
The [endpoints.json](https://github.com/boto/boto/blob/develop/boto/endpoints.json#L426) only lists three endpoints for email/SES, but [the AWS docs](https://docs.aws.amazon.com/general/latest/gr/ses.html) state that there are 8 API endpoints.

```
        "email": {
          "endpoints": {
            "eu-west-1": {}, 
            "us-east-1": {}, 
            "us-west-2": {}
          }
        }, 
```

**Comment by codeandqa** [comment]
Email Receiving Endpoints

Amazon SES doesn't support email receiving in the following Regions: US East (Ohio), US West (N. California) Asia Pacific (Mumbai), Asia Pacific (Seoul), Asia Pacific (Singapore), Asia Pacific (Sydney), Asia Pacific (Tokyo), Canada (Central), Europe (Frankfurt), Europe (London), Europe (Paris), Europe (Stockholm), Middle East (Bahrain), South America (São Paulo), and AWS GovCloud (US).

US East (N. Virginia) | us-east-1 | inbound-smtp.us-east-1.amazonaws.com
US West (Oregon) | us-west-2 | inbound-smtp.us-west-2.amazonaws.com
Europe (Ireland) | eu-west-1 | inbound-smtp.eu-west-1.amazonaws.com

**Comment by kdaily** [comment]
Hi there,

This package is deprecated and no longer supported. Please review the deprecation notice for migration to `boto3`. Thanks!

https://github.com/boto/boto#deprecation-notice
