### ISSUE TITLE
support for on-prem servers?

### ISSUE THREAD

**Issue by tanuj83** [boto/boto#3909]
Hi, does this library work for on-prem servers too or only for AWS ? Please help to provide details if I can use this library on our on-prem servers. 

My Kafka servers in my Data centre not on AWS. how can I use this to encrypt my data at rest?

**Comment by rjdudley** [comment]
Boto is a project for interacting only with AWS.

**Comment by kdaily** [comment]
Hi there,

This package is deprecated and no longer supported. Please review the deprecation notice for migration to `boto3`. Thanks!

https://github.com/boto/boto#deprecation-notice
