### ISSUE TITLE
ModuleNotFoundError: No module named 'boto3'

### ISSUE THREAD

**Issue by shabanalalani** [boto/boto#3912]
I am trying to upload a file to the aws s3 cloud storage. I did the aws configure and everything and the link I was following used a pycharm but I am using thonny. I did instalI boto3 and tried to import boto3 on thonny but it gives me the error above.
Please someone help.

**Comment by kdaily** [comment]
Hi @shabanalalani,

If you're still experiencing this or need assistance, please open up an issue on the `boto3` repository:

https://github.com/boto/boto3/issues/new/choose

Thanks!
