### ISSUE TITLE
boto.utils.get_instance_identity() doesnt support IMDSv2

### ISSUE THREAD

**Issue by rstevens011** [boto/boto#3917]
Looking at https://github.com/boto/boto/blob/develop/boto/utils.py#L411-L430, I don't see a call to get a IMDSv2 token.  Thus, if IMDSv1 is turned off  and the caller is on a EC2 instance, calls to this method will fail

**Comment by kdaily** [comment]
Hi there,

This package is deprecated and no longer supported. Please review the deprecation notice for migration to `boto3`. Thanks!

https://github.com/boto/boto#deprecation-notice
