### ISSUE TITLE
Boto API support for modifying ALB Capacity Configuration

### ISSUE THREAD

**Issue by ahujarajesh** [boto/boto#3918]
Currently there is no AWS CLI / boto API support for modifying ALB Capacity (LCUs).
Reffered: https://docs.aws.amazon.com/cli/latest/reference/elbv2/ and https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/elbv2.html
Its impossible to adjust LCUs via automation as API Support is not available.

Can you please provide the API to modify ALB LCUs.

**Comment by kdaily** [comment]
Hi there,

This package is deprecated and no longer supported. Please review the deprecation notice for migration to `boto3`. Thanks!

https://github.com/boto/boto#deprecation-notice

If you are looking for this feature in `boto3`, please review open issues there, or open a new one:

https://github.com/boto/boto3/issues

Thanks!
