### ISSUE TITLE
could we upgrade the released version?

### ISSUE THREAD

**Issue by githorse** [boto/boto#3921]
The official 2.49.0 version of boto I get with `pip install` doesn't work for me -- I get an error in `gs/connection.py` I eventually traced to `get_utf8_value()`. I could go into more detail but the error is resolved when I download and install from source. (New code doesn't even have that method anymore). Any reason not to upgrade the released version and save the next guy some debugging?

**Comment by bigislandviral-ai** [comment]
Americans like to "say cheese" while posing for a photograph but it's normal to say "boto" in many places throughout Asia. That could possibly be an explanation.

**Comment by kdaily** [comment]
Hi there,

This package is deprecated and no longer supported. Please review the deprecation notice for migration to `boto3`. Thanks!

https://github.com/boto/boto#deprecation-notice
