### ISSUE TITLE
No Support for AWS  me-south-1   region.

### ISSUE THREAD

**Issue by neamanahmed** [boto/boto#3927]
Hi,

I am getting below error  when I run playbook to create ec2 Instance  in me-south-1 Bahrain region
"Region me-south-1 does not seem to be available for aws module boto.ec2. If the region definitely exists, you may need to upgrade boto or extend with endpoints_path "
Next year Dubai in Middle East will be 2nd  region , I am residing in Dubai, and currently bound to use either Europe or USA regions.

**Comment by kdaily** [comment]
Hi @neamanahmed,

This package is deprecated and no longer supported. Please review the deprecation notice for migration to `boto3`. Thanks!

https://github.com/boto/boto#deprecation-notice

**Comment by neamanahmed** [comment]
I have boto3 but still get
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Region me-south-1
does not seem to be available for aws module boto.ec2. If the region
definitely exists, you may need to upgrade boto or extend with
endpoints_path"}
*Neaman Ahmed *
