### ISSUE TITLE
S3 HEAD and PUT intermittently takes upto a minute to execute

### ISSUE THREAD

**Issue by vivekdwy** [boto/boto#3928]
I am using Boto method bucket.get_key() to check the existence of a key in the bucket. This sometimes takes a very long time to execute. As per log tracing, I found that it is taking more than a minute sometimes. The object request I am making every time is having a prefix associated, so this should not have issues with rate limits? Are there improvements in Boto3 for network calls and S3 request slowness?

**Comment by kdaily** [comment]
Hi there,

This package is deprecated and no longer supported. Please review the deprecation notice for migration to `boto3`. Thanks!

https://github.com/boto/boto#deprecation-notice

If you are looking for this feature in `boto3`, please review open issues there, or open a new one:

https://github.com/boto/boto3/issues

Thanks!
