### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by xyb** [boto/boto#3930]
Since Python 3.10 was released a few days ago, maybe boto should do some work to adapt it to avoid error messages like:
```
ImportError: cannot import name 'Mapping' from 'collections'
````

**Comment by alexislg2** [comment]
Why is this issue closed? Is it fixed?

**Comment by nateprewitt** [comment]
Hi @alexislg2, yes Boto3 has supported Python 3.10 since it was released. The issue @xyb is from very old versions of Boto3 that vendored Requests. Any Boto3 release from the last 2 years shouldn't have this issue.

**Comment by alexislg2** [comment]
Yes but Boto3 does not support the MWS API so I need to use boto. I made a fork. I hope boto3 will support MWS someday like boto does.

If anyone has the same issue, you just have to replace `collections.Mapping` by `collections.abc.Mapping`
