### ISSUE TITLE
Accessing non-US S3 buckets causes S3ResponseError

### ISSUE THREAD

**Issue by russss** [boto/boto#443]
The following code, where `eu-west-bucket` is a bucket in the eu-west region:

``` python
import boto
suri = boto.storage_uri('s3://eu-west-bucket/test')
suri.new_key()
```

...raises this error:

```
boto.exception.S3ResponseError: S3ResponseError: 301 Moved Permanently
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message <RequestId>06660583263444FC</RequestId><Bucket>smarkets-db</Bucket><HostId>TCZJTKZ8wo8V1h0xjkOI6grojs/r9IBkhMOcvolXv06QEtxTX89M55aLTPGOo/ht</HostId><Endpoint>eu-west-bucket.s3.amazonaws.com</Endpoint></Error>
```

This appears to have been introduced between 2.0b4 and 2.0rc1. Before 2.0rc1, s3 requests were sent to `bucketname.s3.amazonaws.com`, but now they seem to all go to `s3.amazonaws.com`.  The redirect isn't handled by the HTTP code because that 301 response doesn't appear to include a Location header - it requires you to parse the body of the response to get the URL.

**Comment by mattse** [comment]
I posted a workaround to this problem [here](https://github.com/boto/boto/issues/2836#issuecomment-77283169)

**Comment by stefcloud** [comment]
@mattse's workaround worked for me.  :+1: 

>     if '.' in bucket_name:
        conn = boto.s3.connect_to_region(
                aws_region,
                aws_access_key_id=aws_access_key_id,
                aws_secret_access_key=aws_secret_access_key,
                calling_format=OrdinaryCallingFormat()
                )
    else:
        conn = S3Connection(aws_access_key_id, aws_secret_access_key)

**Comment by JungleKim** [comment]
Thanks, that was very helpful :)

**Comment by muhammad-ammar** [comment]
Getting same issue. Above workaround is not working for me :(

Using Python3 with latest boto.

**Comment by akoren** [comment]
Workaround didn't work, but this thread solved it for me, use bucket.get_location to find out the right location of your bucket, and then reconnect using the new location, the s3.get_bucket worked great for me.

**Comment by serg94** [comment]
in terminal run 'nano ~/.boto'

if there is some configs try to comment or rename file and connect again. (it helps me)

http://boto.cloudhackers.com/en/latest/boto_config_tut.html

there is boto config file directories. take a look one by one and clean them all, it will work by default configs. also configs may be in .bash_profile, .bash_source... 
I guess you must allow only KEY-SECRET
