### ISSUE TITLE
Add support for specifying network interfaces in run_instances call

### ISSUE THREAD

**Issue by nakedible** [boto/boto#672]
The current run_instances call has no support for specifying network interfaces at instance start time.

**Comment by Bustead** [comment]
@nakedible hi mate! Given this issue is 11 years old would you consider closing it? Not sure if this feature has been added to Boto3 but let me know if you want me to investigate. Happy Days :)

**Comment by nakedible** [comment]
No interest in investigating, so I'll just close this off.
