### ISSUE TITLE
wildcard DNS not parsed correctly

### ISSUE THREAD

**Issue by booi** [boto/boto#818]
Creating wildcard DNS entries works but on retrieval they are returned incorrectly. A record retrieved via record = boto.route53.connection.Route53Connection.get_all_rrsets() yields a record.name with '\052' instead of '*'.

"\052.domain.com" instead of "*.domain.com"

\052 is \* in unicode but it doesn't seem to be parsed this way.

**Comment by zimbatm** [comment]
It's also an issue for `zone.find_records('@', 'A')` because `r.name == name` doesn't match. See https://github.com/boto/boto/blob/445f6bf3dc1b61477407c375133d8e975564566c/boto/route53/zone.py#L238

**Comment by booi** [comment]
seems fixed?
