### ISSUE TITLE
S3: ExpiredToken error with IAM's temporary credentials

### ISSUE THREAD

**Issue by khj1218** [boto/boto#898]
'ExpiredToken' errors are occasionally thrown when IAM role's temporary credentials are used.
# --- kvs.py
# --- Note that 'connection' and 'bucket' objects are created once and reused for put requests.

connection = connect_s3()
bucket = connection.get_bucket(bucket_name, False)

def put_raw(bucket, key, value, headers=None):
     k = Key(bucket)
     k.key = key

File "/home/myapp/kvs.py", line 160, in put_raw
    retval = k.set_contents_from_string(value, headers=headers) 
  File "/usr/local/lib/python2.7/dist-packages/boto-2.5.2-py2.7.egg/boto/s3/key.py", line 1129, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.5.2-py2.7.egg/boto/s3/key.py", line 993, in set_contents_from_file
    size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.5.2-py2.7.egg/boto/s3/key.py", line 724, in send_file
    query_args=query_args)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.5.2-py2.7.egg/boto/s3/connection.py", line 470, in make_request
    override_num_retries=override_num_retries)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.5.2-py2.7.egg/boto/connection.py", line 913, in make_request
    return self._mexe(http_request, sender, override_num_retries)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.5.2-py2.7.egg/boto/connection.py", line 790, in _mexe
    request.body, request.headers)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.5.2-py2.7.egg/boto/s3/key.py", line 681, in sender
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><RequestId>A0E4730BE76CC9F0</RequestId><HostId>VdBvtwjLvBhr5QN1VZ2v/LJeBTxso52+q59kmfspLUdbWWnrz714qhXAMMgnvZYV</HostId><Token-0> ... </Token-0></Error>

**Comment by jimfulton** [comment]
FWIW, I get this very rarely with sqs.  Unfortunately, it matters even when it's rare.

I'm going to add some retry logic to our code and, hopefully, shed more light on the issue.

**Comment by Ken1971** [comment]
Yup, it happens very very rare, but it is definitely an important issue. 

For now, I use the clearCredentials public method in AWSCognitoCredentialsProvider as a temp solution on retry.

If this is fixed in future, please notify in this thread. Thanks a lot.

**Comment by bciceron** [comment]
Hello,

I am seeing a lot of these lately, more than once a day.
it started sometime last month but at that point i hadn't seen any for a year.

```
  File "/usr/local/lib/python2.7/dist-packages/boto/sqs/queue.py", line 359, in count
    a = self.get_attributes('ApproximateNumberOfMessages')
  File "/usr/local/lib/python2.7/dist-packages/boto/sqs/queue.py", line 103, in get_attributes
    return self.connection.get_queue_attributes(self, attributes)
  File "/usr/local/lib/python2.7/dist-packages/boto/sqs/connection.py", line 158, in get_queue_attr
ibutes
    Attributes, queue.id)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1207, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.SQSError: SQSError: 403 Forbidden
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>ExpiredToken</Code><Message>The security token included in the request is expired</Message><Detail/></Error><RequestId>bb54bd4b-aabc-56f2-a4ff-f27ac49bde90</RequestId></ErrorResponse>
```

**Comment by felipe-vvoosh** [comment]
I'm having this issue right now... It's getting really annoying already...

**Comment by shacco** [comment]
A year later and im experiencing the same issue.
fatal error: An error occurred (ExpiredToken) when calling the ListObjects operation: The provided token has expired.
This happens when i try
aws s3 cp ./dir s3:bucket

then it stop for ours, and then it happens again

**Comment by rjammala** [comment]
we noticed this even today: 
botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.

**Comment by lpnaunau** [comment]
Same issue here for a couple weeks now: 
boto3.exceptions.S3UploadFailedError: Failed to upload xxx.csv to bucket: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.

**Comment by volodymyrrudyi** [comment]
Same issue with S3 and an app running on an instance with instance profile

**Comment by teamhide** [comment]
Any update here? It occur very rarely but it still happens.

`An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.`

**Comment by avriiil** [comment]
Having this issue now. How to resolve?

**Comment by JSpenced** [comment]
> Having this issue now. How to resolve?

I have had this issue, but it's related to temporary credentials saved in boto sessions that I try to use after the temporary credentials have expired. If your issue is related to that, then the following might help where I reload the boto session's in awswrangler and another custom package, so I don't have to restart my kernels but it will load in the newest temporary credential (probably a better way to do this though):
```
wr.sts.boto3.setup_default_session()
import ocp.secrets
ocp.secrets.secretsmanager = boto3.client("secretsmanager", region_name="us-east-1")
```

**Comment by evaezekwem** [comment]
Still having this issue. Any fix yet?

An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.

Environment details:
OS: 5.4.207-126.363.amzn2int.x86_64 (Amazon Linux)
Arch: x86_64
AWS CLI: 2.7.35

Command that triggered error:
`aws s3 cp ./[some-file] s3://[some-s3-location]`

**Comment by BhagyaLakshmiR** [comment]
I am facing this issue when I generate a new token and use it for the first time. With the same token when I use it again works fine. 
Can someone tell me why I am getting this issue and how can I fix this. Also is there any workaround for this?

The error I am getting is: 
boto3.exceptions.S3UploadFailedError: Failed to upload /aaa/xxx/abc.csv to s3_bucket_folder/abc.csv: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.

**Comment by davclark** [comment]
This issue appears to persist in boto 1.26.71 at least. I'm using an s3.Object.upload_fileobj() call, and getting the above-mentioned `botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the CreateMultipartUpload operation: The provided token has expired.`
