### ISSUE TITLE
boto.ec2.elb:ELBConnection.describe_instance_health uses invalid list params

### ISSUE THREAD

**Issue by winhamwr** [boto/boto#9]
boto.ec2.elb:ELBConnection.describe_instance_health uses the wrong argument to build_list_params which results in all describe_instance_health calls returning every instance on the loadbalancer, regardless of what is passed in the instances argument.

**Comment by mpdehaan** [comment]
I'm currently observing this behavior on 2.3.8, so I'm not positive this fix was merged in.

Obviously adopting Boto3 is a good solution here, but leaving that for future reference.
